from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from analytics import store as _store

STEP = 5000

DDL = """
CREATE TABLE IF NOT EXISTS item_events(
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id BIGINT NOT NULL, ctx TEXT NOT NULL, sub TEXT,
  key TEXT NOT NULL, kind TEXT NOT NULL,
  decision_id BIGINT NOT NULL, turn INTEGER);

CREATE INDEX IF NOT EXISTS ix_ie_camp ON item_events(campaign_id, ctx, decision_id);
CREATE INDEX IF NOT EXISTS ix_ie_key ON item_events(key, kind);

CREATE TABLE IF NOT EXISTS item_event_state(
  campaign_id BIGINT NOT NULL, ctx TEXT NOT NULL, sub TEXT, keys TEXT NOT NULL,
  PRIMARY KEY(campaign_id, ctx));
"""


def _jload(z):
    if not z:
        return {}
    try:
        got = json.loads(z)
    except (TypeError, ValueError):
        return {}
    return got if isinstance(got, dict) else {}


def _equipped(z):
    out = set()
    for it in z.get("equipped") or []:
        if isinstance(it, dict) and it.get("key"):
            out.add(str(it["key"]))
    return out


class _ItemEvents:
    NAME = "item_events"
    TABLES = ("item_events", "item_event_state")
    FORMULA_VERSION = 1
    SOURCE = "decisions"
    DEPENDS_ON = ()
    DDL = DDL

    def safe_hi(self, src, an=None):
        row = src.execute("SELECT MAX(decision_id) m FROM decisions").fetchone()
        return int(row[0] or 0)

    def source_stats(self, src, hi):
        row = src.execute("SELECT MIN(decision_id) m FROM decisions").fetchone()
        return None, row[0]

    def step(self, src, an, lo, hi):
        hi2 = min(hi, lo + STEP)
        decs = {int(r["decision_id"]): (int(r["campaign_id"]),
                                        int(r["turn"]) if r["turn"] is not None
                                        else None)
                for r in src.execute(
                    "SELECT decision_id, campaign_id, turn FROM decisions"
                    " WHERE decision_id > %s AND decision_id <= %s", (lo, hi2))}
        if not decs:
            return hi2, 0
        cids = sorted({cid for cid, _t in decs.values()})
        prev = {(int(r["campaign_id"]), str(r["ctx"])):
                (set(json.loads(r["keys"])), r["sub"])
                for r in an.execute(
                    "SELECT campaign_id, ctx, sub, keys FROM item_event_state"
                    " WHERE campaign_id = ANY(%s)", (cids,))}
        events = []
        for r in src.execute(
                "SELECT e.decision_id, e.context_id, b.z"
                " FROM entities e JOIN blobs b ON b.blob_id = e.features_blob"
                " WHERE e.decision_id > %s AND e.decision_id <= %s"
                " AND e.context_kind = ANY(%s)"
                " ORDER BY e.decision_id",
                (lo, hi2, ["lord", "hero"])):
            did = int(r["decision_id"])
            if did not in decs:
                continue
            cid, turn = decs[did]
            z = _jload(r["z"])
            now = _equipped(z)
            ctx = str(r["context_id"])
            sub = z.get("subtype") or z.get("agent_type")
            sub = str(sub) if sub else None
            was, psub = prev.get((cid, ctx), (None, None))
            if was is None:
                for k in sorted(now):
                    events.append((cid, ctx, sub, k, "on", did, turn))
            else:
                for k in sorted(now - was):
                    events.append((cid, ctx, sub, k, "on", did, turn))
                for k in sorted(was - now):
                    events.append((cid, ctx, sub, k, "off", did, turn))
            prev[(cid, ctx)] = (now, sub or psub)
        if events:
            _store.executemany(
                an,
                "INSERT INTO item_events(campaign_id, ctx, sub, key, kind,"
                " decision_id, turn) VALUES(%s,%s,%s,%s,%s,%s,%s)", events)
        if prev:
            _store.executemany(
                an,
                "INSERT INTO item_event_state VALUES(%s,%s,%s,%s)"
                " ON CONFLICT(campaign_id, ctx) DO UPDATE SET"
                " sub = COALESCE(excluded.sub, item_event_state.sub),"
                " keys = excluded.keys",
                [(cid, ctx, sub, json.dumps(sorted(keys)))
                 for (cid, ctx), (keys, sub) in prev.items()])
        return hi2, len(events)


ITEM_EVENTS = _ItemEvents()

TENANTS = (ITEM_EVENTS,)
