/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_run_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/starts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Starts */
        get: operations["get_starts_api_campaigns_starts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Matrix */
        get: operations["get_matrix_api_campaigns_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Campaigns */
        get: operations["get_campaigns_api_campaigns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Campaign */
        get: operations["get_campaign_api_campaigns__campaign_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Actions */
        get: operations["get_actions_api_decisions_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Menus */
        get: operations["get_menus_api_decisions_menus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timeline */
        get: operations["get_timeline_api_decisions_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions/{decision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Decision */
        get: operations["get_decision_api_decisions__decision_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Decisions */
        get: operations["get_decisions_api_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/forcing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Forcing */
        get: operations["get_forcing_api_models_forcing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/agreement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agreement */
        get: operations["get_agreement_api_models_agreement_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/agreement/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agreement Series
         * @description How agreement has tracked over the run, or by model generation.
         */
        get: operations["get_agreement_series_api_models_agreement_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/agreement/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agreement Breakdown */
        get: operations["get_agreement_breakdown_api_models_agreement_breakdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytics
         * @description What the analytics service has precomputed, and how far behind it is.
         */
        get: operations["get_analytics_api_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Analytics Rebuild
         * @description Ask the analytics service to rebuild from scratch.
         */
        post: operations["post_analytics_rebuild_api_analytics_rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/correlations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Correlations */
        get: operations["get_correlations_api_models_correlations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/training": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Training */
        get: operations["get_training_api_models_training_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Models */
        get: operations["get_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/infra": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Infra */
        get: operations["get_infra_api_infra_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/infra/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Kill */
        post: operations["post_kill_api_infra_kill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/infra/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Launch */
        post: operations["post_launch_api_infra_launch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/infra/coldstart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Coldstart */
        post: operations["post_coldstart_api_infra_coldstart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description Server-sent events: one message whenever the corpus gains rows.
         */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionTypeRow */
        ActionTypeRow: {
            action_type: components["schemas"]["Ident"];
            rate: components["schemas"]["Rate"];
            /** Refusals */
            refusals?: components["schemas"]["Ident"][];
            /**
             * State
             * @default neutral
             * @enum {string}
             */
            state: "ok" | "warn" | "bad" | "neutral";
        };
        /** ActionsPage */
        ActionsPage: {
            scope: components["schemas"]["Scope"];
            /** Tiles */
            tiles: components["schemas"]["Metric"][];
            /** By Type */
            by_type: components["schemas"]["ActionTypeRow"][];
            /** Policies */
            policies: components["schemas"]["PolicyRow"][];
            /**
             * Denominators
             * @description every distinct decision denominator on this page, named. They differ legitimately (one excludes awaiting-execution, one excludes the forced end turn) and were previously all printed as 'decisions'.
             */
            denominators?: components["schemas"]["Count"][];
        };
        /** ActivityRow */
        ActivityRow: {
            /** Stream */
            stream: string;
            /** Last Write */
            last_write?: string | null;
            /** Age Seconds */
            age_seconds?: number | null;
            /**
             * State
             * @default neutral
             * @enum {string}
             */
            state: "ok" | "warn" | "bad" | "neutral";
        };
        /** AgreementBreakdownPage */
        AgreementBreakdownPage: {
            scope: components["schemas"]["Scope"];
            freshness: components["schemas"]["AnalyticsFreshness"];
            /**
             * Dim
             * @enum {string}
             */
            dim: "arm" | "action_type" | "context_kind";
            /** Rows */
            rows?: components["schemas"]["AgreementBreakdownRow"][];
            /** Empty Reason */
            empty_reason?: string | null;
        };
        /** AgreementBreakdownRow */
        AgreementBreakdownRow: {
            key: components["schemas"]["Ident"];
            decisions: components["schemas"]["Count"];
            /** Rho Median */
            rho_median?: number | null;
            /** Rho Mean */
            rho_mean?: number | null;
            /** Tau Mean */
            tau_mean?: number | null;
            /** Rbo Mean */
            rbo_mean?: number | null;
            same_top: components["schemas"]["Rate"];
        };
        /** AgreementPage */
        AgreementPage: {
            scope: components["schemas"]["Scope"];
            freshness: components["schemas"]["AnalyticsFreshness"];
            correlation?: components["schemas"]["CorrelationSummary"] | null;
            /** Rho Bins */
            rho_bins?: components["schemas"]["RhoBin"][];
            /** Summary */
            summary: components["schemas"]["AgreementSummary"][];
            /** Rows */
            rows: components["schemas"]["AgreementRankRow"][];
            /** Secondary */
            secondary?: components["schemas"]["SecondaryMeasure"][];
            /** Warning */
            warning?: string | null;
            /** Empty Reason */
            empty_reason?: string | null;
        };
        /**
         * AgreementRankRow
         * @description Where each model ranked the action that was taken, per deciding strategy.
         */
        AgreementRankRow: {
            picked_by: components["schemas"]["Ident"];
            /** Decisions */
            decisions: number;
            /** Cat Rank */
            cat_rank?: number | null;
            /** Cat Pct */
            cat_pct?: number | null;
            /** Gnn Rank */
            gnn_rank?: number | null;
            /** Gnn Pct */
            gnn_pct?: number | null;
            /** Delta Pct */
            delta_pct?: number | null;
            /** Rho Median */
            rho_median?: number | null;
            /**
             * Fell Back
             * @default 0
             */
            fell_back: number;
        };
        /**
         * AgreementSeriesPage
         * @description Agreement over time, and by model generation.
         */
        AgreementSeriesPage: {
            scope: components["schemas"]["Scope"];
            freshness: components["schemas"]["AnalyticsFreshness"];
            /**
             * Axis
             * @enum {string}
             */
            axis: "window" | "generation";
            /**
             * Is Alignment
             * @default false
             */
            is_alignment: boolean;
            /** Caveat */
            caveat?: string | null;
            /** Bucket Decisions */
            bucket_decisions?: number | null;
            /** Min Decisions */
            min_decisions?: number | null;
            ambiguous: components["schemas"]["Count"];
            /** Points */
            points?: components["schemas"]["AgreementSeriesPoint"][];
            /** Generations */
            generations?: components["schemas"]["GenerationRow"][];
            /** Empty Reason */
            empty_reason?: string | null;
        };
        /** AgreementSeriesPoint */
        AgreementSeriesPoint: {
            /** Label */
            label: string;
            /** Seq */
            seq: number;
            decisions: components["schemas"]["Count"];
            /** From Decision */
            from_decision?: number | null;
            /** To Decision */
            to_decision?: number | null;
            /** From Ts */
            from_ts?: number | null;
            /** To Ts */
            to_ts?: number | null;
            /** Rho Median */
            rho_median?: number | null;
            /** Rho Mean */
            rho_mean?: number | null;
            /** Rho Q1 */
            rho_q1?: number | null;
            /** Rho Q3 */
            rho_q3?: number | null;
            /** Tau Mean */
            tau_mean?: number | null;
            /** Rbo Mean */
            rbo_mean?: number | null;
            same_top: components["schemas"]["Rate"];
            /** Gate */
            gate?: string | null;
        };
        /** AgreementSummary */
        AgreementSummary: {
            /** Measure */
            measure: string;
            /** Value */
            value: string;
            /** Help */
            help?: string | null;
        };
        /**
         * AnalyticsFreshness
         * @description How current the precomputed numbers on this page are.
         */
        AnalyticsFreshness: {
            /** Tenant */
            tenant: string;
            behind: components["schemas"]["Count"];
            rows: components["schemas"]["Count"];
            /** Computed Through */
            computed_through?: number | null;
            /** Age Seconds */
            age_seconds?: number | null;
            /**
             * Formula Version
             * @default 0
             */
            formula_version: number;
            /**
             * State
             * @default neutral
             * @enum {string}
             */
            state: "ok" | "warn" | "bad" | "neutral";
            /** Detail */
            detail?: string | null;
        };
        /** AnalyticsPage */
        AnalyticsPage: {
            scope: components["schemas"]["Scope"];
            /** Tenants */
            tenants?: components["schemas"]["TenantStatus"][];
            /** Db Path */
            db_path: string;
            /** Runner Hint */
            runner_hint: string;
        };
        /** ArmCoverage */
        ArmCoverage: {
            screen: components["schemas"]["Ident"];
            /** Rows */
            rows: number;
            /** Tree Scored */
            tree_scored: number;
            /** Graph Scored */
            graph_scored: number;
            /** Both */
            both: number;
            agree?: components["schemas"]["Rate"] | null;
        };
        /** CampaignDetail */
        CampaignDetail: {
            scope: components["schemas"]["Scope"];
            row: components["schemas"]["CampaignRow"];
            /** Reward */
            reward: components["schemas"]["RewardPoint"][];
            /**
             * Constant Columns
             * @description reward columns holding one distinct value across this campaign; the client hides them by default rather than shipping a dead column
             */
            constant_columns?: string[];
            /** Diplomacy */
            diplomacy: components["schemas"]["DiploEvent"][];
            /** Decisions */
            decisions: components["schemas"]["DecisionRow"][];
        };
        /**
         * CampaignRow
         * @description One campaign, with its outcome joined on.
         */
        CampaignRow: {
            /** Campaign Id */
            campaign_id: number;
            campaign: components["schemas"]["Ident"];
            campaign_map?: components["schemas"]["Ident"] | null;
            /** Turns */
            turns?: number | null;
            /**
             * Decisions
             * @default 0
             */
            decisions: number;
            /**
             * No Action
             * @default 0
             */
            no_action: number;
            /**
             * Attempted
             * @default 0
             */
            attempted: number;
            /**
             * Confirmed
             * @default 0
             */
            confirmed: number;
            confirm_rate?: components["schemas"]["Rate"] | null;
            /** Span Min */
            span_min?: number | null;
            /** Peak Settlements */
            peak_settlements?: number | null;
            /** Peak Power Rank */
            peak_power_rank?: number | null;
            /** Peak Lord Level */
            peak_lord_level?: number | null;
            /** Final Settlements */
            final_settlements?: number | null;
            /** Final Power Rank */
            final_power_rank?: number | null;
            /** Final Income */
            final_income?: number | null;
            /**
             * Turn Rows
             * @default 0
             */
            turn_rows: number;
            /** First Turn */
            first_turn?: number | null;
            /** Last Measured Turn */
            last_measured_turn?: number | null;
            /** Growth Span Turns */
            growth_span_turns?: number | null;
            /** First Settlements */
            first_settlements?: number | null;
            /** First Lord Level */
            first_lord_level?: number | null;
            /** Final Lord Level */
            final_lord_level?: number | null;
            /** Settlements Growth */
            settlements_growth?: number | null;
            /** Lord Growth */
            lord_growth?: number | null;
            /** Settlements Per Turn */
            settlements_per_turn?: number | null;
            /** Lord Per Turn */
            lord_per_turn?: number | null;
            /**
             * Growth State
             * @default no_turn_rows
             * @enum {string}
             */
            growth_state: "measured" | "single_turn" | "no_turn_rows";
            outcome?: components["schemas"]["Ident"] | null;
            /**
             * Outcome State
             * @default neutral
             * @enum {string}
             */
            outcome_state: "ok" | "warn" | "bad" | "neutral";
            /** Ended Because */
            ended_because?: string | null;
            /**
             * Suspicious
             * @default false
             */
            suspicious: boolean;
            /** Ended When */
            ended_when?: string | null;
        };
        /** CampaignsPage */
        CampaignsPage: {
            scope: components["schemas"]["Scope"];
            /** Headline */
            headline: components["schemas"]["OutcomeTally"][];
            suspicious: components["schemas"]["Count"];
            unjoined: components["schemas"]["Count"];
            growth_coverage: components["schemas"]["Rate"];
            /** Rows */
            rows: components["schemas"]["CampaignRow"][];
        };
        /** ControlResult */
        ControlResult: {
            /** Ok */
            ok: boolean;
            /** Steps */
            steps: string[];
        };
        /** CorrelationRow */
        CorrelationRow: {
            arm: components["schemas"]["Ident"];
            /** Campaigns */
            campaigns: number;
            /** Turns */
            turns: number;
            share?: components["schemas"]["Rate"] | null;
            /** Per Campaign */
            per_campaign?: number | null;
            /** Settlements R */
            settlements_r?: number | null;
            /** Settlements Gate */
            settlements_gate?: string | null;
            /** Lord R */
            lord_r?: number | null;
            /** Lord Gate */
            lord_gate?: string | null;
        };
        /**
         * CorrelationSummary
         * @description The headline: how alike the two models' whole orderings are.
         */
        CorrelationSummary: {
            compared: components["schemas"]["Count"];
            coverage: components["schemas"]["Rate"];
            /** Rho Median */
            rho_median?: number | null;
            /** Rho Mean */
            rho_mean?: number | null;
            /** Rho Q1 */
            rho_q1?: number | null;
            /** Rho Q3 */
            rho_q3?: number | null;
            /** Tau Median */
            tau_median?: number | null;
            /** Tau Mean */
            tau_mean?: number | null;
            same_best: components["schemas"]["Rate"];
            /** Overlap Median */
            overlap_median?: number | null;
            /** From Decision */
            from_decision?: number | null;
            /** To Decision */
            to_decision?: number | null;
            /** Excluded */
            excluded?: components["schemas"]["Count"][];
        };
        /**
         * CorrelationTile
         * @description `label` is the tile's identity: "action ranker" or "interrupt model".
         */
        CorrelationTile: {
            /**
             * Label
             * @enum {string}
             */
            label: "action ranker" | "interrupt model";
            /** Rows */
            rows: components["schemas"]["CorrelationRow"][];
        };
        /** CorrelationsPage */
        CorrelationsPage: {
            scope: components["schemas"]["Scope"];
            /** Tiles */
            tiles: components["schemas"]["CorrelationTile"][];
        };
        /**
         * Count
         * @description A number of things, plus the population it counted.
         */
        Count: {
            /** Value */
            value: number;
            /**
             * Noun
             * @description what is being counted, e.g. 'campaigns'
             */
            noun: string;
            /**
             * Population
             * @description which population, e.g. 'with a recorded decision'. Required: a count without its population is the defect this field exists to prevent.
             */
            population: string;
        };
        /**
         * Current
         * @description The campaign being played right now.
         */
        Current: {
            campaign?: components["schemas"]["Ident"] | null;
            /** Turn */
            turn?: number | null;
            /** Settlements */
            settlements?: number | null;
            /** Power Rank */
            power_rank?: number | null;
            /** Lord Level */
            lord_level?: number | null;
            /** Age Seconds */
            age_seconds?: number | null;
        };
        /**
         * DecisionAgreement
         * @description One decision's agreement, for the detail page.
         */
        DecisionAgreement: {
            n: components["schemas"]["Count"];
            /** Status */
            status: string;
            /** Rho */
            rho?: number | null;
            /** Tau B */
            tau_b?: number | null;
            /** Rbo */
            rbo?: number | null;
            /** Top1 Same */
            top1_same?: boolean | null;
            /** Top3 Overlap */
            top3_overlap?: number | null;
            /** Cat Top In Gnn */
            cat_top_in_gnn?: number | null;
            /** Gnn Top In Cat */
            gnn_top_in_cat?: number | null;
            /** Note */
            note?: string | null;
        };
        /** DecisionDetail */
        DecisionDetail: {
            scope: components["schemas"]["Scope"];
            row: components["schemas"]["DecisionRow"];
            agreement?: components["schemas"]["DecisionAgreement"] | null;
            /** Offers */
            offers: components["schemas"]["OfferRow"][];
            /** Entities */
            entities: components["schemas"]["EntityState"][];
            /** Phases */
            phases: components["schemas"]["PhaseSpan"][];
        };
        /** DecisionRow */
        DecisionRow: {
            /** Decision Id */
            decision_id: number;
            /** Ts */
            ts?: number | null;
            campaign?: components["schemas"]["Ident"] | null;
            /** Turn */
            turn?: number | null;
            /** Offers */
            offers?: number | null;
            /** Entity */
            entity?: string | null;
            action_type?: components["schemas"]["Ident"] | null;
            /** Action Key */
            action_key?: string | null;
            result?: components["schemas"]["Ident"] | null;
            /**
             * Result State
             * @default neutral
             * @enum {string}
             */
            result_state: "ok" | "warn" | "bad" | "neutral";
            refusal?: components["schemas"]["Ident"] | null;
            policy?: components["schemas"]["Ident"] | null;
            /** Exploit */
            exploit?: number | null;
            /** Pct Global */
            pct_global?: number | null;
            /** Pct Local */
            pct_local?: number | null;
            /** Cat Rank */
            cat_rank?: number | null;
            /** Gnn Impact */
            gnn_impact?: number | null;
            /** Gnn Rank */
            gnn_rank?: number | null;
            /** Delta Pct */
            delta_pct?: number | null;
            /** Rho */
            rho?: number | null;
            /** Rho N */
            rho_n?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
        };
        /** DecisionsPage */
        DecisionsPage: {
            scope: components["schemas"]["Scope"];
            total: components["schemas"]["Count"];
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Action Types */
            action_types: components["schemas"]["Ident"][];
            /** Policies */
            policies: components["schemas"]["Ident"][];
            /** Results */
            results: components["schemas"]["Ident"][];
            /** Rows */
            rows: components["schemas"]["DecisionRow"][];
        };
        /** DiploEvent */
        DiploEvent: {
            /** Turn */
            turn?: number | null;
            channel?: components["schemas"]["Ident"] | null;
            faction?: components["schemas"]["Ident"] | null;
            outcome?: components["schemas"]["Ident"] | null;
            /** Deal Score */
            deal_score?: number | null;
            /** Standing */
            standing?: number | null;
            /** Terms */
            terms?: string | null;
            /**
             * State
             * @default neutral
             * @enum {string}
             */
            state: "ok" | "warn" | "bad" | "neutral";
        };
        /** EntityState */
        EntityState: {
            /** Context Kind */
            context_kind: string;
            /** Context Id */
            context_id: string;
            /** Features */
            features: {
                [key: string]: unknown;
            };
        };
        /** FitConfigRow */
        FitConfigRow: {
            /** Family */
            family: string;
            /** Role */
            role: string;
            /** Hyperparameters */
            hyperparameters: {
                [key: string]: unknown;
            };
            /** Compute */
            compute: {
                [key: string]: unknown;
            };
        };
        /** ForcingBar */
        ForcingBar: {
            action_type: components["schemas"]["Ident"];
            share: components["schemas"]["Rate"];
            /** Ci Lo */
            ci_lo?: number | null;
            /** Ci Hi */
            ci_hi?: number | null;
        };
        /** ForcingPage */
        ForcingPage: {
            scope: components["schemas"]["Scope"];
            decisions: components["schemas"]["Count"];
            /** Tiles */
            tiles: components["schemas"]["ForcingTile"][];
            /**
             * Empty Reason
             * @description why there is nothing to draw, when there is nothing to draw. The old panel rendered a bare em dash and left the reader to guess.
             */
            empty_reason?: string | null;
        };
        /** ForcingTile */
        ForcingTile: {
            /** Model */
            model: string;
            favours?: components["schemas"]["Ident"] | null;
            /** Bars */
            bars: components["schemas"]["ForcingBar"][];
        };
        /** GenerationRow */
        GenerationRow: {
            trial: components["schemas"]["Ident"];
            /** Generation */
            generation?: number | null;
            /**
             * Retrained
             * @default false
             */
            retrained: boolean;
            /** From Ts */
            from_ts?: number | null;
            /** To Ts */
            to_ts?: number | null;
            /** Overlapped By */
            overlapped_by?: string | null;
            decisions: components["schemas"]["Count"];
            /** Rho Median */
            rho_median?: number | null;
            /** Rho Mean */
            rho_mean?: number | null;
            /** Tau Mean */
            tau_mean?: number | null;
            /** Rbo Mean */
            rbo_mean?: number | null;
            same_top: components["schemas"]["Rate"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Ident
         * @description A game identifier in both forms. `raw` is what you grep; `label` is what you read.
         */
        Ident: {
            /** Raw */
            raw: string;
            /** Label */
            label: string;
            /** Culture */
            culture?: string | null;
            /**
             * Tag
             * @description short run-unique campaign tag
             */
            tag?: string | null;
        };
        /** InfraPage */
        InfraPage: {
            scope: components["schemas"]["Scope"];
            /** Services */
            services: components["schemas"]["Service"][];
            /** Activity */
            activity: components["schemas"]["ActivityRow"][];
            /** Policy Note */
            policy_note: string;
            /** Models */
            models: string[];
            defaults: components["schemas"]["LaunchDefaults"];
            cold_defaults: components["schemas"]["LaunchDefaults"];
            /** Log Tail */
            log_tail: string[];
        };
        /**
         * InterruptOption
         * @description One option on a blocking screen, with its per-model scores as data.
         */
        InterruptOption: {
            label: components["schemas"]["Ident"];
            /** Exploit */
            exploit?: number | null;
            /** Gnn */
            gnn?: number | null;
            /**
             * Chosen
             * @default false
             */
            chosen: boolean;
        };
        /** InterruptRow */
        InterruptRow: {
            /** Interrupt Id */
            interrupt_id: number;
            /** Ts */
            ts?: number | null;
            kind: components["schemas"]["Ident"];
            /** Root */
            root?: string | null;
            campaign?: components["schemas"]["Ident"] | null;
            /** Turn */
            turn?: number | null;
            result?: components["schemas"]["Ident"] | null;
            /**
             * Result State
             * @default neutral
             * @enum {string}
             */
            result_state: "ok" | "warn" | "bad" | "neutral";
            chosen?: components["schemas"]["Ident"] | null;
            /** N Options */
            n_options?: number | null;
            policy?: components["schemas"]["Ident"] | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Options */
            options?: components["schemas"]["InterruptOption"][];
        };
        /** LaunchDefaults */
        LaunchDefaults: {
            /**
             * Campaigns
             * @default 100
             */
            campaigns: number;
            /**
             * Turns Min
             * @default 2
             */
            turns_min: number;
            /**
             * Turns Max
             * @default 20
             */
            turns_max: number;
            /**
             * Retrain First
             * @default true
             */
            retrain_first: boolean;
            /**
             * Retrain Every
             * @default 0
             */
            retrain_every: number;
            /**
             * Model
             * @default catboost
             */
            model: string;
            /**
             * Cfg
             * @default
             */
            cfg: string;
            /**
             * Strategies
             * @default
             */
            strategies: string;
            /**
             * Ruleset
             * @default
             */
            ruleset: string;
            /**
             * Dev
             * @default false
             */
            dev: boolean;
        };
        /** MatrixCell */
        MatrixCell: {
            action_type: components["schemas"]["Ident"];
            rate: components["schemas"]["Rate"];
            /** Total Ms */
            total_ms?: number | null;
            /** Per Try Ms */
            per_try_ms?: number | null;
            /**
             * State
             * @default neutral
             * @enum {string}
             */
            state: "ok" | "warn" | "bad" | "neutral";
        };
        /** MatrixPage */
        MatrixPage: {
            scope: components["schemas"]["Scope"];
            /**
             * Kind
             * @enum {string}
             */
            kind: "action" | "interrupt";
            /** Totals */
            totals: components["schemas"]["MatrixTotal"][];
            /** Columns */
            columns: components["schemas"]["Ident"][];
            /** Rows */
            rows: components["schemas"]["MatrixRow"][];
        };
        /** MatrixRow */
        MatrixRow: {
            faction: components["schemas"]["Ident"];
            /** Cells */
            cells: components["schemas"]["MatrixCell"][];
        };
        /**
         * MatrixTotal
         * @description One row per action type, aggregated across every faction.
         */
        MatrixTotal: {
            action_type: components["schemas"]["Ident"];
            rate: components["schemas"]["Rate"];
            /** Total Ms */
            total_ms?: number | null;
            /** Per Try Ms */
            per_try_ms?: number | null;
            /**
             * State
             * @default neutral
             * @enum {string}
             */
            state: "ok" | "warn" | "bad" | "neutral";
        };
        /** MenusPage */
        MenusPage: {
            scope: components["schemas"]["Scope"];
            total: components["schemas"]["Count"];
            /** By Screen */
            by_screen: components["schemas"]["Count"][];
            /** Policies */
            policies: components["schemas"]["PolicyRow"][];
            /** Coverage */
            coverage: components["schemas"]["ArmCoverage"][];
            /** Rows */
            rows: components["schemas"]["InterruptRow"][];
        };
        /** Metric */
        Metric: {
            /** Label */
            label: string;
            /** Value */
            value?: number | string | null;
            /** Unit */
            unit?: string | null;
            /** Sub */
            sub?: string | null;
            /**
             * State
             * @default neutral
             * @enum {string}
             */
            state: "ok" | "warn" | "bad" | "neutral";
            /** Spark */
            spark?: number[];
        };
        /** ModelCard */
        ModelCard: {
            /** Name */
            name: string;
            /** Role */
            role: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "missing" | "incomplete" | "stale schema";
            /**
             * State
             * @default neutral
             * @enum {string}
             */
            state: "ok" | "warn" | "bad" | "neutral";
            /** Rows */
            rows?: [
                string,
                string
            ][];
            /** Note */
            note?: string | null;
            /** Trained At */
            trained_at?: string | null;
        };
        /** ModelsPage */
        ModelsPage: {
            scope: components["schemas"]["Scope"];
            /** Cards */
            cards: components["schemas"]["ModelCard"][];
            /** Fit */
            fit: components["schemas"]["FitConfigRow"][];
        };
        /** OfferRow */
        OfferRow: {
            /** Rank */
            rank?: number | null;
            /** Entity */
            entity?: string | null;
            action_type?: components["schemas"]["Ident"] | null;
            /** Action Key */
            action_key?: string | null;
            /** Exploit */
            exploit?: number | null;
            /** Pct Global */
            pct_global?: number | null;
            /** Pct Local */
            pct_local?: number | null;
            /** Gnn Impact */
            gnn_impact?: number | null;
            /** Gnn Rank */
            gnn_rank?: number | null;
            /**
             * Taken
             * @default false
             */
            taken: boolean;
        };
        /** OutcomeTally */
        OutcomeTally: {
            outcome: components["schemas"]["Ident"];
            /** Count */
            count: number;
            /**
             * State
             * @default neutral
             * @enum {string}
             */
            state: "ok" | "warn" | "bad" | "neutral";
        };
        /**
         * PhaseSpan
         * @description One phase of one action, in ms.
         */
        PhaseSpan: {
            /**
             * Phase
             * @enum {string}
             */
            phase: "collect" | "queue" | "score" | "verify";
            /** Ms */
            ms: number;
        };
        /** PolicyRow */
        PolicyRow: {
            policy: components["schemas"]["Ident"];
            /** Picks */
            picks: number;
            share: components["schemas"]["Rate"];
            /** Note */
            note?: string | null;
        };
        /**
         * Rate
         * @description A proportion that carries its own denominator.
         */
        Rate: {
            /** N */
            n: number;
            /** Of */
            of: number;
            /** Noun */
            noun: string;
            /** Population */
            population: string;
        };
        /** RewardPoint */
        RewardPoint: {
            /** Turn */
            turn: number;
            /** Income */
            income?: number | null;
            /** Settlements */
            settlements?: number | null;
            /** Allies */
            allies?: number | null;
            /** Vassals */
            vassals?: number | null;
            /** Power Rank */
            power_rank?: number | null;
        };
        /** RhoBin */
        RhoBin: {
            /** Lo */
            lo: number;
            /** Hi */
            hi: number;
            /** Decisions */
            decisions: number;
        };
        /** RunPage */
        RunPage: {
            scope: components["schemas"]["Scope"];
            /** Services */
            services: components["schemas"]["Service"][];
            current: components["schemas"]["Current"];
            /** Throughput */
            throughput: components["schemas"]["Metric"][];
            /** Totals */
            totals: components["schemas"]["Count"][];
            /** Collect Timing */
            collect_timing: components["schemas"]["TimingRow"][];
            /** Cycle Timing */
            cycle_timing: components["schemas"]["TimingRow"][];
            /** Log Tail */
            log_tail: string[];
            /** Log Name */
            log_name?: string | null;
        };
        /**
         * Scope
         * @description One line stating exactly what a section covers. Every section has one.
         */
        Scope: {
            /** Text */
            text: string;
            /** Detail */
            detail?: string | null;
        };
        /**
         * SecondaryMeasure
         * @description A supplement to the rank correlation, never a substitute for it.
         */
        SecondaryMeasure: {
            /** Measure */
            measure: string;
            /** Value */
            value: string;
            rate?: components["schemas"]["Rate"] | null;
        };
        /** Service */
        Service: {
            /** Name */
            name: string;
            /** Up */
            up: boolean;
            /** Pid */
            pid?: number | null;
            /** Started */
            started?: string | null;
            /** Detail */
            detail?: string | null;
        };
        /**
         * StartRow
         * @description One playable start. `n` leads, because most starts have n=1.
         */
        StartRow: {
            faction: components["schemas"]["Ident"];
            /** N */
            n: number;
            /**
             * Single Sample
             * @default false
             */
            single_sample: boolean;
            /** Avg Turns */
            avg_turns?: number | null;
            /** Best Turns */
            best_turns?: number | null;
            /** Best Settlements */
            best_settlements?: number | null;
            /** Best Power Rank */
            best_power_rank?: number | null;
            /** Best Lord Level */
            best_lord_level?: number | null;
            /**
             * Ever Allied
             * @default 0
             */
            ever_allied: number;
            /**
             * Ever Vassal
             * @default 0
             */
            ever_vassal: number;
            confirm_rate?: components["schemas"]["Rate"] | null;
        };
        /** StartsPage */
        StartsPage: {
            scope: components["schemas"]["Scope"];
            low_sample: components["schemas"]["Count"];
            /** Rows */
            rows: components["schemas"]["StartRow"][];
        };
        /** TenantStatus */
        TenantStatus: {
            /** Tenant */
            tenant: string;
            /**
             * Formula Version
             * @default 0
             */
            formula_version: number;
            rows: components["schemas"]["Count"];
            behind: components["schemas"]["Count"];
            /** Watermark */
            watermark?: number | null;
            /** Built */
            built?: string | null;
            /** Last Run */
            last_run?: string | null;
            /** Last Run Seconds */
            last_run_seconds?: number | null;
            /** Last Error */
            last_error?: string | null;
            /**
             * State
             * @default neutral
             * @enum {string}
             */
            state: "ok" | "warn" | "bad" | "neutral";
        };
        /** TimelineAction */
        TimelineAction: {
            /** Decision Id */
            decision_id: number;
            action_type?: components["schemas"]["Ident"] | null;
            /** Action Key */
            action_key?: string | null;
            result?: components["schemas"]["Ident"] | null;
            /**
             * Result State
             * @default neutral
             * @enum {string}
             */
            result_state: "ok" | "warn" | "bad" | "neutral";
            /** Phases */
            phases: components["schemas"]["PhaseSpan"][];
            /** Total Ms */
            total_ms?: number | null;
            /** Gap Ms */
            gap_ms?: number | null;
            /** Unaccounted Ms */
            unaccounted_ms?: number | null;
        };
        /** TimelineLane */
        TimelineLane: {
            campaign: components["schemas"]["Ident"];
            /** Turn */
            turn: number;
            confirmed: components["schemas"]["Rate"];
            /** In Turn S */
            in_turn_s?: number | null;
            /** Actions */
            actions: components["schemas"]["TimelineAction"][];
        };
        /** TimelinePage */
        TimelinePage: {
            scope: components["schemas"]["Scope"];
            /** Phase Legend */
            phase_legend: string[];
            /** Lanes */
            lanes: components["schemas"]["TimelineLane"][];
        };
        /** TimingRow */
        TimingRow: {
            /** Stage */
            stage: string;
            /** Median Ms */
            median_ms?: number | null;
            /** Max Ms */
            max_ms?: number | null;
            /**
             * State
             * @default neutral
             * @enum {string}
             */
            state: "ok" | "warn" | "bad" | "neutral";
        };
        /** TrainingEvent */
        TrainingEvent: {
            /** When */
            when?: string | null;
            /** Trial */
            trial?: string | null;
            /** Corpus Rows */
            corpus_rows?: number | null;
            /** Corpus Campaigns */
            corpus_campaigns?: number | null;
            /** Groups */
            groups?: {
                [key: string]: unknown;
            };
        };
        /** TrainingPage */
        TrainingPage: {
            scope: components["schemas"]["Scope"];
            /** Trials */
            trials: components["schemas"]["TrialRow"][];
            /** History */
            history: components["schemas"]["TrainingEvent"][];
            /** Group Order */
            group_order: string[];
        };
        /** TrialRow */
        TrialRow: {
            /** Trial */
            trial: string;
            /**
             * Snapshots
             * @description how many ledger lines this trial wrote. The ledger appends a snapshot per campaign as a trial progresses, so one trial owns many lines; the row shows its newest state and this says how many were folded in.
             * @default 1
             */
            snapshots: number;
            /** Backend */
            backend?: string | null;
            /** Cfg */
            cfg?: string | null;
            /** Mix */
            mix?: {
                [key: string]: unknown;
            };
            /** Ruleset */
            ruleset?: string | null;
            /** Campaigns */
            campaigns?: number | null;
            /** Corpus */
            corpus?: number | null;
            /** Settlements Per Campaign */
            settlements_per_campaign?: number | null;
            /** Settlements Total */
            settlements_total?: number | null;
            grew?: components["schemas"]["Rate"] | null;
            shrank?: components["schemas"]["Rate"] | null;
            /**
             * Growth Baseline
             * @description which definition this row was measured on. Rows written before the clamp was removed are not comparable with rows written after it.
             */
            growth_baseline?: string | null;
            /** Lord Per Campaign */
            lord_per_campaign?: number | null;
            /** Turns Per Campaign */
            turns_per_campaign?: number | null;
            /** Seconds Per Campaign */
            seconds_per_campaign?: number | null;
            /** Seconds Per Turn */
            seconds_per_turn?: number | null;
            /** Notes */
            notes?: string | null;
            /**
             * Live
             * @default false
             */
            live: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_run_api_run_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
        };
    };
    get_starts_api_campaigns_starts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartsPage"];
                };
            };
        };
    };
    get_matrix_api_campaigns_matrix_get: {
        parameters: {
            query?: {
                kind?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatrixPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_campaigns_api_campaigns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignsPage"];
                };
            };
        };
    };
    get_campaign_api_campaigns__campaign_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_actions_api_decisions_actions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionsPage"];
                };
            };
        };
    };
    get_menus_api_decisions_menus_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenusPage"];
                };
            };
        };
    };
    get_timeline_api_decisions_timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelinePage"];
                };
            };
        };
    };
    get_decision_api_decisions__decision_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decision_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_decisions_api_decisions_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                action_type?: string | null;
                policy?: string | null;
                result?: string | null;
                campaign?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_forcing_api_models_forcing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForcingPage"];
                };
            };
        };
    };
    get_agreement_api_models_agreement_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementPage"];
                };
            };
        };
    };
    get_agreement_series_api_models_agreement_series_get: {
        parameters: {
            query?: {
                axis?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementSeriesPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agreement_breakdown_api_models_agreement_breakdown_get: {
        parameters: {
            query?: {
                dim?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementBreakdownPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytics_api_analytics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsPage"];
                };
            };
        };
    };
    post_analytics_rebuild_api_analytics_rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlResult"];
                };
            };
        };
    };
    get_correlations_api_models_correlations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationsPage"];
                };
            };
        };
    };
    get_training_api_models_training_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingPage"];
                };
            };
        };
    };
    get_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsPage"];
                };
            };
        };
    };
    get_infra_api_infra_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfraPage"];
                };
            };
        };
    };
    post_kill_api_infra_kill_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlResult"];
                };
            };
        };
    };
    post_launch_api_infra_launch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LaunchDefaults"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_coldstart_api_infra_coldstart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LaunchDefaults"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
