port = 55433
listen_addresses = 'localhost'
max_connections = 50

shared_buffers = 8GB
effective_cache_size = 32GB
work_mem = 64MB
maintenance_work_mem = 2047MB
max_locks_per_transaction = 512

max_wal_size = 8GB
min_wal_size = 1GB
checkpoint_timeout = 15min
checkpoint_completion_target = 0.9
wal_compression = zstd
wal_buffers = 64MB

random_page_cost = 1.1
effective_io_concurrency = 0

max_worker_processes = 24
max_parallel_workers_per_gather = 4
max_parallel_maintenance_workers = 8

autovacuum_vacuum_cost_delay = 0
autovacuum_naptime = 30s

logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d.log'
log_rotation_age = 1d
log_min_duration_statement = 500ms
log_checkpoints = on
log_line_prefix = '%m [%p] %a '
track_io_timing = on
