from __future__ import annotations

import glob
import json
import os
import sys
import time

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(_HERE))

import common
from decisions import pg

POLL = 3.0
MARK = "TWSTATE "
CHUNK = 4 * 1024 * 1024

DDL = """
CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.game_event(
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts DOUBLE PRECISION NOT NULL,
  campaign_key TEXT, turn INTEGER, faction TEXT,
  event TEXT NOT NULL, in_player_turn SMALLINT,
  payload TEXT NOT NULL);

CREATE INDEX IF NOT EXISTS ix_game_event_campaign
  ON app.game_event(campaign_key, turn, event_id);
CREATE INDEX IF NOT EXISTS ix_game_event_kind ON app.game_event(event);

CREATE TABLE IF NOT EXISTS app.game_event_state(
  src TEXT PRIMARY KEY, offset_bytes BIGINT NOT NULL, seen DOUBLE PRECISION);
"""

DROP_KEYS = ("kind", "event", "turn", "faction", "in_player_turn")


def _db():
    con = pg.connect(autocommit=True)
    for stmt in [s.strip() for s in DDL.split(";") if s.strip()]:
        con.execute(stmt)
    return con


def _offsets(con):
    cur = con.cursor()
    cur.execute("SELECT src, offset_bytes FROM app.game_event_state")
    return {r[0]: int(r[1]) for r in cur.fetchall()}


def _save_offset(con, src, off):
    con.cursor().execute(
        "INSERT INTO app.game_event_state VALUES(%s,%s,%s)"
        " ON CONFLICT(src) DO UPDATE SET offset_bytes=excluded.offset_bytes, seen=excluded.seen",
        (src, int(off), time.time()))


def _sources(log_dirs):
    out = []
    for d in log_dirs or ():
        for p in glob.glob(os.path.join(d, "script_log_*.txt")):
            out.append(p)
    return sorted(out)


def _thin(rec):
    return {k: v for k, v in rec.items()
            if v is not None and v != "" and k not in DROP_KEYS}


def _rows_from(chunk, player, campaign_key, now):
    rows = []
    for line in chunk.decode("utf-8", "replace").splitlines():
        i = line.find(MARK)
        if i < 0:
            continue
        try:
            rec = json.loads(line[i + len(MARK):])
        except (ValueError, json.JSONDecodeError):
            continue
        if rec.get("kind") != "event":
            continue
        fac = rec.get("faction")
        if player and fac and fac != player:
            continue
        rows.append((now, campaign_key, rec.get("turn"), fac, rec.get("event"),
                     1 if rec.get("in_player_turn") else 0,
                     json.dumps(_thin(rec), separators=(",", ":"))))
    return rows


def _player_and_campaign(bus):
    try:
        from bus import Bus
        b = bus or Bus()
        import collect
        cs = collect.campaign_state(b)
        return cs.get("faction"), cs.get("campaign_uuid")
    except Exception:
        return None, None


def run(ctx, log_dirs=None):
    sys.path.insert(0, common.BUS)
    sys.path.insert(0, common.DECISIONS)
    from bus import Bus
    bus = Bus()
    con = _db()
    offsets = _offsets(con)
    player = campaign_key = None
    last_ident = 0.0
    written = 0
    sys.stderr.write("events: tailing %d log dir(s) every %.1fs\n"
                     % (len(log_dirs or ()), POLL))
    while ctx.is_running():
        try:
            if time.time() - last_ident > 20.0:
                p, c = _player_and_campaign(bus)
                if p:
                    player, campaign_key = p, c
                last_ident = time.time()
            for src in _sources(log_dirs):
                try:
                    size = os.path.getsize(src)
                except OSError:
                    continue
                off = offsets.get(src, size)
                if size < off:
                    off = 0
                if size <= off:
                    offsets[src] = off
                    continue
                with open(src, "rb") as fh:
                    fh.seek(off)
                    chunk = fh.read(min(CHUNK, size - off))
                cut = chunk.rfind(b"\n")
                if cut < 0:
                    continue
                chunk, off = chunk[:cut + 1], off + cut + 1
                rows = _rows_from(chunk, player, campaign_key, time.time())
                if rows:
                    con.cursor().executemany(
                        "INSERT INTO app.game_event(ts, campaign_key, turn, faction,"
                        " event, in_player_turn, payload) VALUES(%s,%s,%s,%s,%s,%s,%s)",
                        rows)
                    written += len(rows)
                    ctx.emit({"kind": "game_events", "src": os.path.basename(src),
                              "rows": len(rows), "total": written,
                              "campaign": campaign_key})
                offsets[src] = off
                _save_offset(con, src, off)
        except Exception as e:
            ctx.on_error("events", e)
        common.wait("events_poll", POLL)
    con.close()
