from __future__ import annotations

MAX_ENTITIES_PER_DECISION = 1 << 16
MAX_OFFERS_PER_DECISION = 1 << 20

SCORE_FIELDS = ("score", "exploit", "rank", "pct_global", "gnn_impact", "gnn_rank")

MODEL_SCORE_FIELDS = ("score", "rank")

RANKED_ARMS = ("greedy_catboost", "marwil_gnn", "greedy_gnn")
RANK_SOURCE = {"greedy_catboost": ("scores", SCORE_FIELDS.index("rank")),
               "marwil_gnn": ("scores", SCORE_FIELDS.index("gnn_rank")),
               "greedy_gnn": ("model_scores", MODEL_SCORE_FIELDS.index("rank"))}
PAIRS = tuple((a, b) for i, a in enumerate(RANKED_ARMS) for b in RANKED_ARMS[i + 1:])


def pair_key(a, b):
    return "%s|%s" % (a, b)


def pair_of(key):
    a, _, b = str(key or "").partition("|")
    return (a, b) if (a, b) in PAIRS else None


SCHEMA_VERSION = "pg1"

DDL = """
CREATE TABLE IF NOT EXISTS meta(k TEXT PRIMARY KEY, v TEXT);

CREATE TABLE IF NOT EXISTS collector_versions(
  version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collector_sha TEXT NOT NULL UNIQUE, git_sha TEXT, started_ts DOUBLE PRECISION, note TEXT);

CREATE TABLE IF NOT EXISTS blobs(
  blob_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sha TEXT NOT NULL UNIQUE, n INTEGER NOT NULL, z TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS actions(
  action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  context_kind TEXT NOT NULL, context_id TEXT NOT NULL,
  action_type TEXT NOT NULL, action_key TEXT NOT NULL, params TEXT NOT NULL,
  UNIQUE(context_kind, context_id, action_type, action_key, params));

CREATE TABLE IF NOT EXISTS campaigns(
  campaign_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_key TEXT NOT NULL UNIQUE, faction TEXT, campaign_map TEXT,
  presave_radius DOUBLE PRECISION, selector TEXT, picked_ts DOUBLE PRECISION,
  difficulty INTEGER, leader TEXT,
  first_decision_id BIGINT, last_decision_id BIGINT,
  outcome TEXT, defeated SMALLINT, turns INTEGER);

CREATE TABLE IF NOT EXISTS decisions(
  decision_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id BIGINT NOT NULL REFERENCES campaigns(campaign_id),
  ts DOUBLE PRECISION, turn INTEGER, decision_seq INTEGER NOT NULL DEFAULT 0,
  policy TEXT, version_id BIGINT REFERENCES collector_versions(version_id),
  n_entities INTEGER NOT NULL, n_offers INTEGER NOT NULL,
  campaign_blob BIGINT REFERENCES blobs(blob_id),
  world_blob BIGINT REFERENCES blobs(blob_id),
  timings TEXT,
  income DOUBLE PRECISION, settlements DOUBLE PRECISION, allies DOUBLE PRECISION,
  vassals DOUBLE PRECISION, power_rank DOUBLE PRECISION, lord_level DOUBLE PRECISION);

CREATE TABLE IF NOT EXISTS entities(
  decision_id BIGINT NOT NULL, entity_seq INTEGER NOT NULL,
  context_kind TEXT NOT NULL, context_id TEXT NOT NULL,
  features_blob BIGINT NOT NULL REFERENCES blobs(blob_id),
  PRIMARY KEY(decision_id, entity_seq));

CREATE TABLE IF NOT EXISTS offers(
  decision_id BIGINT NOT NULL, offer_seq INTEGER NOT NULL,
  entity_seq INTEGER NOT NULL, action_id BIGINT NOT NULL REFERENCES actions(action_id),
  PRIMARY KEY(decision_id, offer_seq));

CREATE TABLE IF NOT EXISTS taken(
  decision_id BIGINT PRIMARY KEY,
  offer_seq INTEGER, entity_seq INTEGER, action_id BIGINT,
  ts DOUBLE PRECISION, executed SMALLINT NOT NULL, confirmed SMALLINT NOT NULL,
  counted SMALLINT NOT NULL,
  refusal TEXT, confirm_signal TEXT, confirm_before TEXT, confirm_after TEXT,
  latency_ms INTEGER, policy TEXT, timing TEXT, diagnostics TEXT,
  campaign_id BIGINT);

CREATE TABLE IF NOT EXISTS offer_scores(
  decision_id BIGINT NOT NULL, offer_seq INTEGER NOT NULL,
  score DOUBLE PRECISION, exploit DOUBLE PRECISION, rank DOUBLE PRECISION,
  pct_global DOUBLE PRECISION,
  gnn_impact DOUBLE PRECISION, gnn_rank DOUBLE PRECISION,
  PRIMARY KEY(decision_id, offer_seq));

CREATE TABLE IF NOT EXISTS offer_model_scores(
  decision_id BIGINT NOT NULL, offer_seq INTEGER NOT NULL, model TEXT NOT NULL,
  score DOUBLE PRECISION, rank DOUBLE PRECISION,
  PRIMARY KEY(decision_id, offer_seq, model));

CREATE TABLE IF NOT EXISTS interrupts(
  interrupt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts DOUBLE PRECISION, campaign_id BIGINT REFERENCES campaigns(campaign_id), turn INTEGER,
  kind TEXT NOT NULL, root TEXT, root_context TEXT,
  n_options INTEGER, options_json TEXT, chosen TEXT, chosen_context TEXT,
  executed SMALLINT, confirmed SMALLINT, counted SMALLINT, refusal TEXT, latency_ms INTEGER,
  campaign_blob BIGINT REFERENCES blobs(blob_id),
  world_blob BIGINT REFERENCES blobs(blob_id),
  panel_blob BIGINT REFERENCES blobs(blob_id),
  policy TEXT);

CREATE TABLE IF NOT EXISTS rpc_requests(
  rpc_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  req_id TEXT UNIQUE, kind TEXT NOT NULL, ts DOUBLE PRECISION NOT NULL, payload TEXT);

CREATE TABLE IF NOT EXISTS rpc_responses(
  req_id TEXT PRIMARY KEY, ts DOUBLE PRECISION NOT NULL,
  decision_id BIGINT, payload TEXT, error TEXT);

CREATE TABLE IF NOT EXISTS postmortems(
  postmortem_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_key TEXT, ts DOUBLE PRECISION, run_dir TEXT,
  faction TEXT, turn INTEGER, outcome TEXT, defeated SMALLINT,
  reason TEXT, payload TEXT);

CREATE TABLE IF NOT EXISTS diplomacy_events(
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts DOUBLE PRECISION, campaign_key TEXT, turn INTEGER, kind TEXT, payload TEXT);

CREATE TABLE IF NOT EXISTS ucb_picks(
  pick_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts DOUBLE PRECISION NOT NULL, c DOUBLE PRECISION, total_plays INTEGER,
  campaign_map TEXT, faction TEXT,
  n INTEGER, mean DOUBLE PRECISION, explore DOUBLE PRECISION, score DOUBLE PRECISION,
  tied INTEGER, blend DOUBLE PRECISION, entropy DOUBLE PRECISION, std DOUBLE PRECISION);

CREATE TABLE IF NOT EXISTS ucb_pick_rows(
  pick_id BIGINT NOT NULL, rank INTEGER NOT NULL,
  campaign_map TEXT, faction TEXT,
  n INTEGER, mean DOUBLE PRECISION, explore DOUBLE PRECISION, score DOUBLE PRECISION,
  chosen SMALLINT, blend DOUBLE PRECISION, entropy DOUBLE PRECISION, std DOUBLE PRECISION,
  PRIMARY KEY(pick_id, rank));

CREATE INDEX IF NOT EXISTS ix_dec_campaign ON decisions(campaign_id, decision_id);
CREATE INDEX IF NOT EXISTS ix_dec_turn ON decisions(turn);
CREATE INDEX IF NOT EXISTS ix_dec_ts ON decisions(ts);
CREATE INDEX IF NOT EXISTS ix_taken_ts ON taken(ts);
CREATE INDEX IF NOT EXISTS ix_taken_counted ON taken(counted);
CREATE INDEX IF NOT EXISTS ix_diplo_ev ON diplomacy_events(campaign_key, event_id);
CREATE INDEX IF NOT EXISTS ix_ucb_picks_ts ON ucb_picks(ts);
CREATE INDEX IF NOT EXISTS ix_dec_gains ON decisions(
  campaign_id, decision_id, ts, turn, settlements, lord_level, allies, vassals);
CREATE INDEX IF NOT EXISTS ix_dec_turn_bounds ON decisions(campaign_id, turn, decision_id);
CREATE INDEX IF NOT EXISTS ix_taken_agg ON taken(
  campaign_id, action_id, policy, refusal, counted, latency_ms, ts);
CREATE INDEX IF NOT EXISTS ix_taken_action ON taken(action_id);
CREATE INDEX IF NOT EXISTS ix_offers_action ON offers(action_id);
CREATE INDEX IF NOT EXISTS ix_interrupts_campaign ON interrupts(campaign_id, interrupt_id);
CREATE INDEX IF NOT EXISTS ix_rpc_req_id ON rpc_requests(rpc_id);
"""


CAMPAIGN_SCALARS = ("income", "settlements", "allies", "vassals",
                    "power_rank", "lord_level")


VIEWS = """
CREATE OR REPLACE VIEW decision_points AS
SELECT d.decision_id AS decision_id, d.ts AS ts, c.campaign_key AS campaign_id,
       d.turn AS turn, d.decision_seq AS decision_seq, d.policy AS policy,
       d.n_entities AS n_entities, d.n_offers AS n_offers,
       bc.z AS campaign, bw.z AS world, d.timings AS timings
FROM decisions d
LEFT JOIN campaigns c ON c.campaign_id = d.campaign_id
LEFT JOIN blobs bc ON bc.blob_id = d.campaign_blob
LEFT JOIN blobs bw ON bw.blob_id = d.world_blob;

CREATE OR REPLACE VIEW entity_snapshots AS
SELECT (e.decision_id * {ES} + e.entity_seq) AS snapshot_id, e.decision_id AS decision_id,
       e.context_kind AS context_kind, e.context_id AS context_id,
       b.z AS features
FROM entities e JOIN blobs b ON b.blob_id = e.features_blob;

DROP VIEW IF EXISTS action_offers;
CREATE VIEW action_offers AS
SELECT (o.decision_id * {OS} + o.offer_seq) AS offer_id, o.decision_id AS decision_id,
       (o.decision_id * {ES} + o.entity_seq) AS snapshot_id,
       a.context_kind AS context_kind, a.context_id AS context_id,
       a.action_type AS action_type, a.action_key AS action_key,
       a.params AS params,
       os.score AS score, os.exploit AS exploit, os.rank AS rank,
       os.pct_global AS pct_global,
       os.gnn_impact AS gnn_impact, os.gnn_rank AS gnn_rank,
       oms.score AS ggnn_score, oms.rank AS ggnn_rank
FROM offers o
LEFT JOIN actions a ON a.action_id = o.action_id
LEFT JOIN offer_scores os ON os.decision_id = o.decision_id AND os.offer_seq = o.offer_seq
LEFT JOIN offer_model_scores oms ON oms.decision_id = o.decision_id
     AND oms.offer_seq = o.offer_seq AND oms.model = 'greedy_gnn';

CREATE OR REPLACE VIEW action_taken AS
SELECT t.decision_id AS taken_id, t.decision_id AS decision_id,
       (t.decision_id * {ES} + t.entity_seq) AS snapshot_id,
       (t.decision_id * {OS} + t.offer_seq) AS offer_id,
       t.ts AS ts, a.context_kind AS context_kind, a.context_id AS context_id,
       a.action_type AS action_type, a.action_key AS action_key,
       t.executed AS executed, t.confirmed AS confirmed, t.counted AS counted,
       t.refusal AS refusal, t.confirm_signal AS confirm_signal,
       t.confirm_before AS confirm_before, t.confirm_after AS confirm_after,
       t.latency_ms AS latency_ms, t.policy AS policy, t.timing AS timing,
       t.diagnostics AS diagnostics
FROM taken t LEFT JOIN actions a ON a.action_id = t.action_id;

CREATE OR REPLACE VIEW turn_bounds AS
SELECT campaign_id, turn,
       MIN(decision_id) AS open_id, MAX(decision_id) AS close_id
FROM decisions GROUP BY campaign_id, turn;

CREATE OR REPLACE VIEW turn_open AS
SELECT c.campaign_key AS campaign_id, d.turn AS turn, d.ts AS ts,
       d.decision_id AS decision_id,
       d.income AS income, d.settlements AS settlements, d.allies AS allies,
       d.vassals AS vassals, d.power_rank AS power_rank, d.lord_level AS lord_level
FROM turn_bounds tb
JOIN decisions d ON d.decision_id = tb.open_id
LEFT JOIN campaigns c ON c.campaign_id = d.campaign_id;

CREATE OR REPLACE VIEW turn_close AS
SELECT c.campaign_key AS campaign_id, d.turn AS turn, d.ts AS ts,
       d.decision_id AS decision_id,
       d.income AS income, d.settlements AS settlements, d.allies AS allies,
       d.vassals AS vassals, d.power_rank AS power_rank, d.lord_level AS lord_level
FROM turn_bounds tb
JOIN decisions d ON d.decision_id = tb.close_id
LEFT JOIN campaigns c ON c.campaign_id = d.campaign_id;

CREATE OR REPLACE VIEW interrupt_decisions AS
SELECT i.interrupt_id AS interrupt_id, i.ts AS ts, c.campaign_key AS campaign_id,
       i.turn AS turn, i.kind AS kind, i.root AS root, i.root_context AS root_context,
       i.n_options AS n_options, i.options_json AS options_json,
       i.chosen AS chosen, i.chosen_context AS chosen_context,
       bc.z AS campaign_json, i.executed AS executed, i.confirmed AS confirmed,
       i.counted AS counted, i.refusal AS refusal, i.latency_ms AS latency_ms,
       NULL AS tree_json, i.policy AS policy,
       bw.z AS world_json, bp.z AS panel_json
FROM interrupts i
LEFT JOIN campaigns c ON c.campaign_id = i.campaign_id
LEFT JOIN blobs bc ON bc.blob_id = i.campaign_blob
LEFT JOIN blobs bw ON bw.blob_id = i.world_blob
LEFT JOIN blobs bp ON bp.blob_id = i.panel_blob;

CREATE OR REPLACE VIEW start_counts AS
SELECT c.campaign_map AS campaign_map, c.faction AS faction, COUNT(*) AS n
FROM campaigns c
WHERE (SELECT COUNT(*) FROM decisions d WHERE d.campaign_id = c.campaign_id) >= 2
GROUP BY c.campaign_map, c.faction;

CREATE OR REPLACE VIEW campaign_gains AS
SELECT c.campaign_map AS campaign_map, c.faction AS faction,
       c.campaign_key AS campaign_key, agg.first_ts AS first_ts,
       agg.turns_reached AS turns_reached,
       COALESCE(agg.peak_settlements, 0) - COALESCE(f.settlements, 0) AS settlements_gained,
       COALESCE(agg.peak_lord_level, 0) - COALESCE(f.lord_level, 0) AS levels_gained,
       COALESCE(agg.peak_allies, 0) - COALESCE(f.allies, 0) AS allies_gained,
       COALESCE(agg.peak_vassals, 0) - COALESCE(f.vassals, 0) AS vassals_gained
FROM (SELECT campaign_id, COUNT(*) AS n, MIN(decision_id) AS first_id,
             MIN(ts) AS first_ts, COALESCE(MAX(turn), 0) AS turns_reached,
             MAX(settlements) AS peak_settlements,
             MAX(lord_level) AS peak_lord_level,
             MAX(allies) AS peak_allies, MAX(vassals) AS peak_vassals
      FROM decisions GROUP BY campaign_id) agg
JOIN decisions f ON f.decision_id = agg.first_id
LEFT JOIN campaigns c ON c.campaign_id = agg.campaign_id
WHERE agg.n >= 2;
""".format(ES=MAX_ENTITIES_PER_DECISION, OS=MAX_OFFERS_PER_DECISION)


LAYOUT_INVARIANT = (
    "SELECT count(*) FROM decisions d WHERE d.n_offers != "
    "(SELECT count(*) FROM offers o WHERE o.decision_id = d.decision_id)")
