from __future__ import annotations

import json
import os
import sys
import time

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(_HERE))

from decisions import pg

DDL = """
CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.starts(
  start_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_map TEXT NOT NULL, faction TEXT NOT NULL,
  leader TEXT NOT NULL DEFAULT '', difficulty DOUBLE PRECISION,
  UNIQUE(campaign_map, faction, leader, difficulty));

CREATE TABLE IF NOT EXISTS app.experiments(
  experiment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE, config TEXT NOT NULL DEFAULT '{}',
  created_ts DOUBLE PRECISION NOT NULL, status TEXT NOT NULL DEFAULT 'stopped',
  note TEXT);

CREATE TABLE IF NOT EXISTS app.segments(
  segment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  experiment_id BIGINT NOT NULL REFERENCES app.experiments(experiment_id),
  seq INTEGER NOT NULL, started_ts DOUBLE PRECISION NOT NULL,
  code_version TEXT, note TEXT, params TEXT,
  UNIQUE(experiment_id, seq));

CREATE TABLE IF NOT EXISTS app.campaign_tags(
  campaign_key TEXT PRIMARY KEY,
  start_id BIGINT REFERENCES app.starts(start_id),
  experiment_id BIGINT REFERENCES app.experiments(experiment_id),
  segment_id BIGINT REFERENCES app.segments(segment_id));

CREATE TABLE IF NOT EXISTS app.boards(
  board_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE, ord INTEGER NOT NULL DEFAULT 0,
  created_ts DOUBLE PRECISION NOT NULL);

CREATE TABLE IF NOT EXISTS app.views(
  view_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_id BIGINT NOT NULL REFERENCES app.boards(board_id) ON DELETE CASCADE,
  name TEXT NOT NULL, spec TEXT NOT NULL, ord INTEGER NOT NULL DEFAULT 0,
  created_ts DOUBLE PRECISION NOT NULL);

CREATE TABLE IF NOT EXISTS app.settings(k TEXT PRIMARY KEY, v TEXT NOT NULL);

CREATE INDEX IF NOT EXISTS ix_segments_exp ON app.segments(experiment_id, seq);
CREATE INDEX IF NOT EXISTS ix_tags_exp ON app.campaign_tags(experiment_id);
CREATE INDEX IF NOT EXISTS ix_tags_start ON app.campaign_tags(start_id);
CREATE INDEX IF NOT EXISTS ix_views_board ON app.views(board_id, ord);
"""

DEFAULT_SCORE = {"settlements": 1.0, "income_per_100": 1.0, "allies": 0.0, "techs": 0.0}

DEFAULT_SETTINGS = {
    "score": DEFAULT_SCORE,
    "home_map_frame": "owned_adjacent",
    "home_characters": "all",
    "include_bot_campaigns": True,
}

SEED_BOARD = "Exclusive choices"

SEED_VIEWS = (
    ("Opening research · first pick", {
        "record": "research",
        "computed": [{"name": "opening",
                      "expr": "CASE WHEN turn <= 3 THEN 'first three turns'"
                              " WHEN turn <= 10 THEN 'turns 4-10' ELSE 'later' END"}],
        "rows": ["opening"],
        "columns": [],
        "values": [{"field": "*", "agg": "share", "label": "share"},
                   {"field": "turn", "agg": "median", "label": "turn, median"}],
        "filters": [{"field": "researched", "op": "=", "value": 1}],
        "chart": "table"}),
    ("Settlement size · public order", {
        "record": "regions",
        "computed": [{"name": "size_band",
                      "expr": "CASE WHEN buildings >= 4 THEN 'large'"
                              " WHEN buildings >= 2 THEN 'mid' ELSE 'small' END"}],
        "rows": ["size_band"],
        "columns": [],
        "values": [{"field": "*", "agg": "share", "label": "share"},
                   {"field": "public_order", "agg": "median", "label": "order, median"},
                   {"field": "income", "agg": "median", "label": "income, median"}],
        "filters": [{"field": "mine", "op": "=", "value": 1}],
        "chart": "bars"}),
)


def ensure(con=None):
    own = con is None
    con = con or pg.connect(autocommit=True)
    for stmt in [s.strip() for s in DDL.split(";") if s.strip()]:
        con.execute(stmt)
    cur = con.cursor()
    cur.execute("SELECT COUNT(*) FROM app.boards")
    if cur.fetchone()[0] == 0:
        cur.execute("INSERT INTO app.boards(name, ord, created_ts) VALUES(%s,0,%s)"
                    " RETURNING board_id", (SEED_BOARD, time.time()))
        bid = cur.fetchone()[0]
        for i, (name, spec) in enumerate(SEED_VIEWS):
            cur.execute(
                "INSERT INTO app.views(board_id, name, spec, ord, created_ts)"
                " VALUES(%s,%s,%s,%s,%s)",
                (bid, name, json.dumps(spec), i, time.time()))
    if own:
        con.close()


def settings(con=None):
    own = con is None
    con = con or pg.connect(autocommit=True)
    ensure(con)
    cur = con.cursor()
    cur.execute("SELECT k, v FROM app.settings")
    got = dict(DEFAULT_SETTINGS)
    for k, v in cur.fetchall():
        try:
            got[k] = json.loads(v)
        except (ValueError, TypeError):
            got[k] = v
    if own:
        con.close()
    return got


def save_settings(values, con=None):
    own = con is None
    con = con or pg.connect(autocommit=True)
    ensure(con)
    cur = con.cursor()
    for k, v in values.items():
        cur.execute("INSERT INTO app.settings VALUES(%s,%s)"
                    " ON CONFLICT(k) DO UPDATE SET v=excluded.v",
                    (k, json.dumps(v)))
    if own:
        con.close()
    return settings(con if not own else None)


def start_id(campaign_map, faction, leader, difficulty, con=None):
    own = con is None
    con = con or pg.connect(autocommit=True)
    ensure(con)
    cur = con.cursor()
    args = (campaign_map or "", faction or "", leader or "",
            None if difficulty is None else float(difficulty))
    cur.execute(
        "INSERT INTO app.starts(campaign_map, faction, leader, difficulty)"
        " VALUES(%s,%s,%s,%s) ON CONFLICT DO NOTHING", args)
    cur.execute(
        "SELECT start_id FROM app.starts WHERE campaign_map=%s AND faction=%s"
        " AND leader=%s AND difficulty IS NOT DISTINCT FROM %s", args)
    row = cur.fetchone()
    if own:
        con.close()
    return row[0] if row else None


def sync_starts(con=None):
    own = con is None
    con = con or pg.connect(autocommit=True)
    ensure(con)
    cur = con.cursor()
    cur.execute(
        "INSERT INTO app.starts(campaign_map, faction, leader, difficulty)"
        " SELECT DISTINCT COALESCE(campaign_map,''), COALESCE(faction,''),"
        " COALESCE(leader,''), difficulty FROM campaigns"
        " WHERE faction IS NOT NULL ON CONFLICT DO NOTHING")
    cur.execute(
        "INSERT INTO app.campaign_tags(campaign_key, start_id)"
        " SELECT c.campaign_key, s.start_id FROM campaigns c"
        " JOIN app.starts s ON s.campaign_map = COALESCE(c.campaign_map,'')"
        "  AND s.faction = COALESCE(c.faction,'')"
        "  AND s.leader = COALESCE(c.leader,'')"
        "  AND s.difficulty IS NOT DISTINCT FROM c.difficulty"
        " ON CONFLICT(campaign_key) DO UPDATE SET start_id=excluded.start_id")
    cur.execute("SELECT COUNT(*) FROM app.starts")
    n = cur.fetchone()[0]
    if own:
        con.close()
    return n


def experiment(name, config=None, note=None, con=None):
    own = con is None
    con = con or pg.connect(autocommit=True)
    ensure(con)
    cur = con.cursor()
    cur.execute("INSERT INTO app.experiments(name, config, created_ts, note)"
                " VALUES(%s,%s,%s,%s) ON CONFLICT(name) DO UPDATE SET config=excluded.config"
                " RETURNING experiment_id",
                (name, json.dumps(config or {}), time.time(), note))
    eid = cur.fetchone()[0]
    if own:
        con.close()
    return eid


def open_segment(experiment_id, code_version=None, note=None, params=None, con=None):
    own = con is None
    con = con or pg.connect(autocommit=True)
    ensure(con)
    cur = con.cursor()
    cur.execute("SELECT COALESCE(MAX(seq),0)+1 FROM app.segments WHERE experiment_id=%s",
                (experiment_id,))
    seq = cur.fetchone()[0]
    cur.execute(
        "INSERT INTO app.segments(experiment_id, seq, started_ts, code_version, note, params)"
        " VALUES(%s,%s,%s,%s,%s,%s) RETURNING segment_id",
        (experiment_id, seq, time.time(), code_version, note,
         json.dumps(params or {})))
    sid = cur.fetchone()[0]
    cur.execute("UPDATE app.experiments SET status='live' WHERE experiment_id=%s",
                (experiment_id,))
    if own:
        con.close()
    return sid, seq


def tag_campaign(campaign_key, experiment_id=None, segment_id=None, con=None):
    own = con is None
    con = con or pg.connect(autocommit=True)
    ensure(con)
    con.cursor().execute(
        "INSERT INTO app.campaign_tags(campaign_key, experiment_id, segment_id)"
        " VALUES(%s,%s,%s) ON CONFLICT(campaign_key) DO UPDATE SET"
        " experiment_id=COALESCE(excluded.experiment_id, app.campaign_tags.experiment_id),"
        " segment_id=COALESCE(excluded.segment_id, app.campaign_tags.segment_id)",
        (campaign_key, experiment_id, segment_id))
    if own:
        con.close()
