ALTER TABLE dict.action ADD CONSTRAINT action_action_type_id_fkey FOREIGN KEY (action_type_id) REFERENCES dict.action_type;
ALTER TABLE corpus.campaign ADD CONSTRAINT campaign_faction_id_fkey FOREIGN KEY (faction_id) REFERENCES dict.faction;
ALTER TABLE corpus.campaign ADD CONSTRAINT campaign_campaign_map_id_fkey FOREIGN KEY (campaign_map_id) REFERENCES dict.campaign_map;
ALTER TABLE corpus.campaign ADD CONSTRAINT campaign_selector_id_fkey FOREIGN KEY (selector_id) REFERENCES dict.selector;
ALTER TABLE corpus.campaign ADD CONSTRAINT campaign_outcome_id_fkey FOREIGN KEY (outcome_id) REFERENCES dict.enum;
CREATE INDEX campaign_faction_map ON corpus.campaign (campaign_map_id, faction_id, campaign_id);
CREATE INDEX campaign_first_ts ON corpus.campaign (first_ts DESC NULLS LAST);
CREATE INDEX campaign_first_snapshot ON corpus.campaign (first_snapshot_id DESC NULLS LAST);
ALTER TABLE corpus.snapshot ADD CONSTRAINT snapshot_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES corpus.campaign;
ALTER TABLE corpus.snapshot ADD CONSTRAINT snapshot_kind_id_fkey FOREIGN KEY (kind_id) REFERENCES dict.enum;
ALTER TABLE corpus.snapshot ADD CONSTRAINT snapshot_version_id_fkey FOREIGN KEY (version_id) REFERENCES corpus.collector_version;
CREATE INDEX snapshot_campaign_ts ON corpus.snapshot (campaign_id, ts, snapshot_id);
CREATE INDEX snapshot_campaign_turn ON corpus.snapshot (campaign_id, turn, snapshot_id) INCLUDE (kind_id);
CREATE INDEX snapshot_ts ON corpus.snapshot (ts);
ALTER TABLE corpus.decision ADD CONSTRAINT decision_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES corpus.snapshot;
ALTER TABLE corpus.decision_timing ADD CONSTRAINT decision_timing_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES corpus.decision;
ALTER TABLE corpus.interrupt ADD CONSTRAINT interrupt_interrupt_id_fkey FOREIGN KEY (interrupt_id) REFERENCES corpus.snapshot;
ALTER TABLE corpus.interrupt ADD CONSTRAINT interrupt_prev_decision_id_fkey FOREIGN KEY (prev_decision_id) REFERENCES corpus.decision;
ALTER TABLE corpus.interrupt ADD CONSTRAINT interrupt_state_at_id_fkey FOREIGN KEY (state_at_id) REFERENCES dict.enum;
ALTER TABLE corpus.interrupt ADD CONSTRAINT interrupt_kind_id_fkey FOREIGN KEY (kind_id) REFERENCES dict.enum;
ALTER TABLE corpus.interrupt ADD CONSTRAINT interrupt_dilemma_id_fkey FOREIGN KEY (dilemma_id) REFERENCES dict.dilemma;
ALTER TABLE corpus.interrupt ADD CONSTRAINT interrupt_incident_id_fkey FOREIGN KEY (incident_id) REFERENCES dict.incident;
ALTER TABLE corpus.interrupt ADD CONSTRAINT interrupt_region_id_fkey FOREIGN KEY (region_id) REFERENCES dict.region;
ALTER TABLE corpus.interrupt ADD CONSTRAINT interrupt_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES dict.enum;
ALTER TABLE corpus.interrupt ADD CONSTRAINT interrupt_refusal_id_fkey FOREIGN KEY (refusal_id) REFERENCES dict.enum;
CREATE INDEX interrupt_prev_decision ON corpus.interrupt (prev_decision_id);
CREATE INDEX interrupt_kind ON corpus.interrupt (kind_id, interrupt_id);
ALTER TABLE corpus.snapshot_campaign ADD CONSTRAINT snapshot_campaign_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES corpus.snapshot;
ALTER TABLE corpus.snapshot_campaign ADD CONSTRAINT snapshot_campaign_faction_id_fkey FOREIGN KEY (faction_id) REFERENCES dict.faction;
ALTER TABLE corpus.snapshot_campaign ADD CONSTRAINT snapshot_campaign_game_version_id_fkey FOREIGN KEY (game_version_id) REFERENCES dict.game_version;
ALTER TABLE corpus.snapshot_campaign ADD CONSTRAINT snapshot_campaign_selector_id_fkey FOREIGN KEY (selector_id) REFERENCES dict.selector;
ALTER TABLE corpus.snapshot_campaign ADD CONSTRAINT snapshot_campaign_campaign_map_id_fkey FOREIGN KEY (campaign_map_id) REFERENCES dict.campaign_map;
ALTER TABLE corpus.snapshot_campaign ADD CONSTRAINT snapshot_campaign_resource_set_id_fkey FOREIGN KEY (resource_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.snapshot_campaign ADD CONSTRAINT snapshot_campaign_hero_count_set_id_fkey FOREIGN KEY (hero_count_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.snapshot_campaign ADD CONSTRAINT snapshot_campaign_effect_bundle_set_id_fkey FOREIGN KEY (effect_bundle_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.snapshot_read_failure ADD CONSTRAINT snapshot_read_failure_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES corpus.snapshot;
ALTER TABLE corpus.snapshot_world ADD CONSTRAINT snapshot_world_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES corpus.snapshot;
ALTER TABLE corpus.snapshot_world ADD CONSTRAINT snapshot_world_region_set_id_fkey FOREIGN KEY (region_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.snapshot_world ADD CONSTRAINT snapshot_world_settlement_set_id_fkey FOREIGN KEY (settlement_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.snapshot_world ADD CONSTRAINT snapshot_world_ruin_set_id_fkey FOREIGN KEY (ruin_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.snapshot_world ADD CONSTRAINT snapshot_world_enemy_agent_set_id_fkey FOREIGN KEY (enemy_agent_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.snapshot_world ADD CONSTRAINT snapshot_world_war_graph_set_id_fkey FOREIGN KEY (war_graph_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.snapshot_world ADD CONSTRAINT snapshot_world_relation_set_id_fkey FOREIGN KEY (relation_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.snapshot_world ADD CONSTRAINT snapshot_world_stationed_set_id_fkey FOREIGN KEY (stationed_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.world_army ADD CONSTRAINT world_army_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES corpus.snapshot;
ALTER TABLE corpus.world_army ADD CONSTRAINT world_army_subtype_id_fkey FOREIGN KEY (subtype_id) REFERENCES dict.agent_subtype;
ALTER TABLE corpus.world_army ADD CONSTRAINT world_army_agent_type_id_fkey FOREIGN KEY (agent_type_id) REFERENCES dict.agent_type;
ALTER TABLE corpus.world_army ADD CONSTRAINT world_army_stance_id_fkey FOREIGN KEY (stance_id) REFERENCES dict.stance;
ALTER TABLE corpus.world_army ADD CONSTRAINT world_army_region_owner_id_fkey FOREIGN KEY (region_owner_id) REFERENCES dict.faction;
ALTER TABLE corpus.world_army ADD CONSTRAINT world_army_region_id_fkey FOREIGN KEY (region_id) REFERENCES dict.region;
ALTER TABLE corpus.world_army ADD CONSTRAINT world_army_province_id_fkey FOREIGN KEY (province_id) REFERENCES dict.province;
ALTER TABLE corpus.world_hostile ADD CONSTRAINT world_hostile_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES corpus.snapshot;
ALTER TABLE corpus.world_hostile ADD CONSTRAINT world_hostile_kind_id_fkey FOREIGN KEY (kind_id) REFERENCES dict.enum;
ALTER TABLE corpus.world_hostile ADD CONSTRAINT world_hostile_faction_id_fkey FOREIGN KEY (faction_id) REFERENCES dict.faction;
ALTER TABLE corpus.world_hostile ADD CONSTRAINT world_hostile_subtype_id_fkey FOREIGN KEY (subtype_id) REFERENCES dict.agent_subtype;
ALTER TABLE corpus.world_hostile ADD CONSTRAINT world_hostile_agent_type_id_fkey FOREIGN KEY (agent_type_id) REFERENCES dict.agent_type;
ALTER TABLE corpus.world_hostile ADD CONSTRAINT world_hostile_province_id_fkey FOREIGN KEY (province_id) REFERENCES dict.province;
ALTER TABLE corpus.world_hostile ADD CONSTRAINT world_hostile_region_id_fkey FOREIGN KEY (region_id) REFERENCES dict.region;
ALTER TABLE corpus.world_hostile ADD CONSTRAINT world_hostile_stance_id_fkey FOREIGN KEY (stance_id) REFERENCES dict.stance;
ALTER TABLE corpus.character ADD CONSTRAINT character_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES corpus.campaign;
ALTER TABLE corpus.snapshot_entity ADD CONSTRAINT snapshot_entity_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES corpus.snapshot;
ALTER TABLE corpus.snapshot_entity ADD CONSTRAINT snapshot_entity_kind_id_fkey FOREIGN KEY (kind_id) REFERENCES dict.enum;
ALTER TABLE corpus.snapshot_entity ADD CONSTRAINT snapshot_entity_character_id_fkey FOREIGN KEY (character_id) REFERENCES corpus.character;
ALTER TABLE corpus.snapshot_entity ADD CONSTRAINT snapshot_entity_region_id_fkey FOREIGN KEY (region_id) REFERENCES dict.region;
CREATE INDEX snapshot_entity_character ON corpus.snapshot_entity (character_id, snapshot_id) WHERE character_id IS NOT NULL;
CREATE INDEX snapshot_entity_region ON corpus.snapshot_entity (region_id, snapshot_id) WHERE region_id IS NOT NULL;
ALTER TABLE corpus.char_state ADD CONSTRAINT char_state_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES corpus.snapshot;
ALTER TABLE corpus.char_state ADD CONSTRAINT char_state_character_id_fkey FOREIGN KEY (character_id) REFERENCES corpus.character;
ALTER TABLE corpus.char_state ADD CONSTRAINT char_state_stance_id_fkey FOREIGN KEY (stance_id) REFERENCES dict.stance;
ALTER TABLE corpus.char_state ADD CONSTRAINT char_state_subtype_id_fkey FOREIGN KEY (subtype_id) REFERENCES dict.agent_subtype;
ALTER TABLE corpus.char_state ADD CONSTRAINT char_state_region_id_fkey FOREIGN KEY (region_id) REFERENCES dict.region;
ALTER TABLE corpus.char_state ADD CONSTRAINT char_state_agent_type_id_fkey FOREIGN KEY (agent_type_id) REFERENCES dict.agent_type;
ALTER TABLE corpus.char_state ADD CONSTRAINT char_state_skill_set_id_fkey FOREIGN KEY (skill_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.char_state ADD CONSTRAINT char_state_stance_set_id_fkey FOREIGN KEY (stance_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.char_state ADD CONSTRAINT char_state_recruitable_set_id_fkey FOREIGN KEY (recruitable_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.char_state ADD CONSTRAINT char_state_unit_card_set_id_fkey FOREIGN KEY (unit_card_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.char_state ADD CONSTRAINT char_state_pending_queue_set_id_fkey FOREIGN KEY (pending_queue_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.char_state ADD CONSTRAINT char_state_equipped_set_id_fkey FOREIGN KEY (equipped_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.char_state ADD CONSTRAINT char_state_horde_slot_set_id_fkey FOREIGN KEY (horde_slot_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.char_state ADD CONSTRAINT char_state_merc_pool_set_id_fkey FOREIGN KEY (merc_pool_set_id) REFERENCES corpus.state_set;
CREATE INDEX char_state_character ON corpus.char_state (character_id, snapshot_id DESC);
ALTER TABLE corpus.char_state_ext ADD CONSTRAINT char_state_ext_trait_set_id_fkey FOREIGN KEY (trait_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.char_state_ext ADD CONSTRAINT char_state_ext_trait_progress_set_id_fkey FOREIGN KEY (trait_progress_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.char_state_ext ADD CONSTRAINT char_state_ext_background_skill_id_fkey FOREIGN KEY (background_skill_id) REFERENCES dict.skill;
ALTER TABLE corpus.char_state_ext ADD CONSTRAINT char_state_ext_hidden_skill_state_set_id_fkey FOREIGN KEY (hidden_skill_state_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.char_state_ext ADD CONSTRAINT char_state_ext_effect_bundle_set_id_fkey FOREIGN KEY (effect_bundle_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.char_state_ext ADD CONSTRAINT char_state_ext_force_effect_bundle_set_id_fkey FOREIGN KEY (force_effect_bundle_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.char_state_ext ADD CONSTRAINT char_state_ext_fk1 FOREIGN KEY (snapshot_id, character_id) REFERENCES corpus.char_state;
ALTER TABLE corpus.province_state ADD CONSTRAINT province_state_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES corpus.snapshot;
ALTER TABLE corpus.province_state ADD CONSTRAINT province_state_region_id_fkey FOREIGN KEY (region_id) REFERENCES dict.region;
ALTER TABLE corpus.province_state ADD CONSTRAINT province_state_province_id_fkey FOREIGN KEY (province_id) REFERENCES dict.province;
ALTER TABLE corpus.province_state ADD CONSTRAINT province_state_selected_edict_id_fkey FOREIGN KEY (selected_edict_id) REFERENCES dict.edict;
ALTER TABLE corpus.province_state ADD CONSTRAINT province_state_active_edict_id_fkey FOREIGN KEY (active_edict_id) REFERENCES dict.edict;
ALTER TABLE corpus.province_state ADD CONSTRAINT province_state_built_set_id_fkey FOREIGN KEY (built_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.province_state ADD CONSTRAINT province_state_building_now_set_id_fkey FOREIGN KEY (building_now_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.province_state ADD CONSTRAINT province_state_corruption_set_id_fkey FOREIGN KEY (corruption_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.province_state ADD CONSTRAINT province_state_buildable_set_id_fkey FOREIGN KEY (buildable_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.province_state ADD CONSTRAINT province_state_slot_state_set_id_fkey FOREIGN KEY (slot_state_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.province_state ADD CONSTRAINT province_state_effect_bundle_set_id_fkey FOREIGN KEY (effect_bundle_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.province_state ADD CONSTRAINT province_state_plague_bundle_set_id_fkey FOREIGN KEY (plague_bundle_set_id) REFERENCES corpus.state_set;
CREATE INDEX province_state_region ON corpus.province_state (region_id, snapshot_id DESC);
ALTER TABLE corpus.campaign_state ADD CONSTRAINT campaign_state_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES corpus.snapshot;
ALTER TABLE corpus.campaign_state ADD CONSTRAINT campaign_state_tech_set_id_fkey FOREIGN KEY (tech_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.campaign_state ADD CONSTRAINT campaign_state_rite_set_id_fkey FOREIGN KEY (rite_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.campaign_state ADD CONSTRAINT campaign_state_lord_pool_set_id_fkey FOREIGN KEY (lord_pool_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.campaign_state ADD CONSTRAINT campaign_state_anc_pool_set_id_fkey FOREIGN KEY (anc_pool_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.campaign_state ADD CONSTRAINT campaign_state_equipped_all_set_id_fkey FOREIGN KEY (equipped_all_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.campaign_state ADD CONSTRAINT campaign_state_mission_set_id_fkey FOREIGN KEY (mission_set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.campaign_state ADD CONSTRAINT campaign_state_current_research_id_fkey FOREIGN KEY (current_research_id) REFERENCES dict.tech_node;
ALTER TABLE corpus.skill_set_member ADD CONSTRAINT skill_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.skill_set_member ADD CONSTRAINT skill_set_member_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES dict.skill;
ALTER TABLE corpus.skill_set_member ADD CONSTRAINT skill_set_member_status_id_fkey FOREIGN KEY (status_id) REFERENCES dict.enum;
ALTER TABLE corpus.stance_set_member ADD CONSTRAINT stance_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.stance_set_member ADD CONSTRAINT stance_set_member_stance_id_fkey FOREIGN KEY (stance_id) REFERENCES dict.stance;
ALTER TABLE corpus.recruitable_set_member ADD CONSTRAINT recruitable_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.recruitable_set_member ADD CONSTRAINT recruitable_set_member_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES dict.unit;
ALTER TABLE corpus.hidden_skill_state_set_member ADD CONSTRAINT hidden_skill_state_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.hidden_skill_state_set_member ADD CONSTRAINT hidden_skill_state_set_member_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES dict.skill;
ALTER TABLE corpus.trait_set_member ADD CONSTRAINT trait_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.trait_set_member ADD CONSTRAINT trait_set_member_trait_id_fkey FOREIGN KEY (trait_id) REFERENCES dict.trait;
ALTER TABLE corpus.trait_set_member ADD CONSTRAINT trait_set_member_level_key_id_fkey FOREIGN KEY (level_key_id) REFERENCES dict.trait_level;
ALTER TABLE corpus.trait_progress_set_member ADD CONSTRAINT trait_progress_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.trait_progress_set_member ADD CONSTRAINT trait_progress_set_member_trait_id_fkey FOREIGN KEY (trait_id) REFERENCES dict.trait;
ALTER TABLE corpus.item_slot_set_member ADD CONSTRAINT item_slot_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.item_slot_set_member ADD CONSTRAINT item_slot_set_member_ancillary_id_fkey FOREIGN KEY (ancillary_id) REFERENCES dict.ancillary;
ALTER TABLE corpus.horde_slot_set_member ADD CONSTRAINT horde_slot_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.horde_slot_set_member ADD CONSTRAINT horde_slot_set_member_building_id_fkey FOREIGN KEY (building_id) REFERENCES dict.building;
ALTER TABLE corpus.merc_pool_set_member ADD CONSTRAINT merc_pool_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.merc_pool_set_member ADD CONSTRAINT merc_pool_set_member_action_id_fkey FOREIGN KEY (action_id) REFERENCES dict.enum;
ALTER TABLE corpus.merc_pool_set_member ADD CONSTRAINT merc_pool_set_member_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES dict.unit;
ALTER TABLE corpus.pending_queue_set_member ADD CONSTRAINT pending_queue_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.pending_queue_set_member ADD CONSTRAINT pending_queue_set_member_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES dict.unit;
ALTER TABLE corpus.effect_bundle_set_member ADD CONSTRAINT effect_bundle_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.effect_bundle_set_member ADD CONSTRAINT effect_bundle_set_member_effect_bundle_id_fkey FOREIGN KEY (effect_bundle_id) REFERENCES dict.effect_bundle;
ALTER TABLE corpus.unit_card_set_member ADD CONSTRAINT unit_card_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.unit_card_set_member ADD CONSTRAINT unit_card_set_member_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES dict.unit;
ALTER TABLE corpus.unit_card_set_member ADD CONSTRAINT unit_card_set_member_category_id_fkey FOREIGN KEY (category_id) REFERENCES dict.unit_category;
ALTER TABLE corpus.buildable_set_member ADD CONSTRAINT buildable_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.buildable_set_member ADD CONSTRAINT buildable_set_member_building_id_fkey FOREIGN KEY (building_id) REFERENCES dict.building;
ALTER TABLE corpus.slot_state_set_member ADD CONSTRAINT slot_state_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.slot_state_set_member ADD CONSTRAINT slot_state_set_member_queued_building_id_fkey FOREIGN KEY (queued_building_id) REFERENCES dict.building;
ALTER TABLE corpus.slot_state_set_member ADD CONSTRAINT slot_state_set_member_building_id_fkey FOREIGN KEY (building_id) REFERENCES dict.building;
ALTER TABLE corpus.built_set_member ADD CONSTRAINT built_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.built_set_member ADD CONSTRAINT built_set_member_building_id_fkey FOREIGN KEY (building_id) REFERENCES dict.building;
ALTER TABLE corpus.building_now_set_member ADD CONSTRAINT building_now_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.building_now_set_member ADD CONSTRAINT building_now_set_member_building_id_fkey FOREIGN KEY (building_id) REFERENCES dict.building;
ALTER TABLE corpus.resource_set_member ADD CONSTRAINT resource_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.resource_set_member ADD CONSTRAINT resource_set_member_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES dict.pooled_resource;
ALTER TABLE corpus.hero_count_set_member ADD CONSTRAINT hero_count_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.hero_count_set_member ADD CONSTRAINT hero_count_set_member_agent_type_id_fkey FOREIGN KEY (agent_type_id) REFERENCES dict.agent_type;
ALTER TABLE corpus.tech_set_member ADD CONSTRAINT tech_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.tech_set_member ADD CONSTRAINT tech_set_member_tech_node_id_fkey FOREIGN KEY (tech_node_id) REFERENCES dict.tech_node;
ALTER TABLE corpus.rite_set_member ADD CONSTRAINT rite_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.rite_set_member ADD CONSTRAINT rite_set_member_ritual_id_fkey FOREIGN KEY (ritual_id) REFERENCES dict.ritual;
ALTER TABLE corpus.rite_set_member ADD CONSTRAINT rite_set_member_reason_id_fkey FOREIGN KEY (reason_id) REFERENCES dict.rite_reason;
ALTER TABLE corpus.lord_pool_set_member ADD CONSTRAINT lord_pool_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.lord_pool_set_member ADD CONSTRAINT lord_pool_set_member_subtype_id_fkey FOREIGN KEY (subtype_id) REFERENCES dict.agent_subtype;
ALTER TABLE corpus.lord_pool_candidate ADD CONSTRAINT lord_pool_candidate_bg_skill_id_fkey FOREIGN KEY (bg_skill_id) REFERENCES dict.skill;
ALTER TABLE corpus.lord_pool_candidate ADD CONSTRAINT lord_pool_candidate_cand_subtype_id_fkey FOREIGN KEY (cand_subtype_id) REFERENCES dict.agent_subtype;
ALTER TABLE corpus.lord_pool_candidate ADD CONSTRAINT lord_pool_candidate_fk1 FOREIGN KEY (set_id, subtype_id) REFERENCES corpus.lord_pool_set_member(set_id, subtype_id);
ALTER TABLE corpus.mission_set_member ADD CONSTRAINT mission_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.mission_set_member ADD CONSTRAINT mission_set_member_mission_id_fkey FOREIGN KEY (mission_id) REFERENCES dict.mission;
ALTER TABLE corpus.mission_set_member ADD CONSTRAINT mission_set_member_status_id_fkey FOREIGN KEY (status_id) REFERENCES dict.enum;
ALTER TABLE corpus.mission_set_member ADD CONSTRAINT mission_set_member_issuer_id_fkey FOREIGN KEY (issuer_id) REFERENCES dict.mission_issuer;
ALTER TABLE corpus.region_set_member ADD CONSTRAINT region_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.region_set_member ADD CONSTRAINT region_set_member_region_id_fkey FOREIGN KEY (region_id) REFERENCES dict.region;
ALTER TABLE corpus.region_set_member ADD CONSTRAINT region_set_member_province_id_fkey FOREIGN KEY (province_id) REFERENCES dict.province;
ALTER TABLE corpus.region_set_member ADD CONSTRAINT region_set_member_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES dict.faction;
ALTER TABLE corpus.settlement_set_member ADD CONSTRAINT settlement_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.settlement_set_member ADD CONSTRAINT settlement_set_member_region_id_fkey FOREIGN KEY (region_id) REFERENCES dict.region;
ALTER TABLE corpus.ruin_set_member ADD CONSTRAINT ruin_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.ruin_set_member ADD CONSTRAINT ruin_set_member_region_id_fkey FOREIGN KEY (region_id) REFERENCES dict.region;
ALTER TABLE corpus.enemy_agent_set_member ADD CONSTRAINT enemy_agent_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.enemy_agent_set_member ADD CONSTRAINT enemy_agent_set_member_faction_id_fkey FOREIGN KEY (faction_id) REFERENCES dict.faction;
ALTER TABLE corpus.war_graph_set_member ADD CONSTRAINT war_graph_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.war_graph_set_member ADD CONSTRAINT war_graph_set_member_faction_id_fkey FOREIGN KEY (faction_id) REFERENCES dict.faction;
ALTER TABLE corpus.relation_set_member ADD CONSTRAINT relation_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.relation_set_member ADD CONSTRAINT relation_set_member_faction_id_fkey FOREIGN KEY (faction_id) REFERENCES dict.faction;
ALTER TABLE corpus.stationed_set_member ADD CONSTRAINT stationed_set_member_set_id_fkey FOREIGN KEY (set_id) REFERENCES corpus.state_set;
ALTER TABLE corpus.stationed_set_member ADD CONSTRAINT stationed_set_member_region_id_fkey FOREIGN KEY (region_id) REFERENCES dict.region;
ALTER TABLE corpus.offer ADD CONSTRAINT offer_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES corpus.decision;
ALTER TABLE corpus.offer ADD CONSTRAINT offer_action_id_fkey FOREIGN KEY (action_id) REFERENCES dict.action;
ALTER TABLE corpus.offer ADD CONSTRAINT offer_fk1 FOREIGN KEY (decision_id, entity_seq) REFERENCES corpus.snapshot_entity(snapshot_id, entity_seq);
CREATE INDEX offer_action ON corpus.offer (action_id, decision_id);
ALTER TABLE corpus.taken ADD CONSTRAINT taken_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES corpus.decision;
ALTER TABLE corpus.taken ADD CONSTRAINT taken_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES corpus.campaign;
ALTER TABLE corpus.taken ADD CONSTRAINT taken_action_id_fkey FOREIGN KEY (action_id) REFERENCES dict.action;
ALTER TABLE corpus.taken ADD CONSTRAINT taken_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES dict.enum;
ALTER TABLE corpus.taken ADD CONSTRAINT taken_refusal_id_fkey FOREIGN KEY (refusal_id) REFERENCES dict.enum;
ALTER TABLE corpus.taken ADD CONSTRAINT taken_confirm_signal_id_fkey FOREIGN KEY (confirm_signal_id) REFERENCES dict.confirm_signal;
ALTER TABLE corpus.taken ADD CONSTRAINT taken_failed_precheck_id_fkey FOREIGN KEY (failed_precheck_id) REFERENCES dict.enum;
CREATE INDEX taken_campaign ON corpus.taken (campaign_id, decision_id) INCLUDE (action_id, policy_id, latency_ms);
CREATE INDEX taken_campaign_ts ON corpus.taken (campaign_id, ts DESC) INCLUDE (decision_id, action_id, refusal_id);
CREATE INDEX taken_ts ON corpus.taken (ts);
CREATE INDEX taken_action ON corpus.taken (action_id);
ALTER TABLE corpus.interrupt_option ADD CONSTRAINT interrupt_option_interrupt_id_fkey FOREIGN KEY (interrupt_id) REFERENCES corpus.interrupt;
ALTER TABLE corpus.interrupt_battle_panel ADD CONSTRAINT interrupt_battle_panel_interrupt_id_fkey FOREIGN KEY (interrupt_id) REFERENCES corpus.interrupt;
ALTER TABLE corpus.interrupt_diplo_panel ADD CONSTRAINT interrupt_diplo_panel_interrupt_id_fkey FOREIGN KEY (interrupt_id) REFERENCES corpus.interrupt;
ALTER TABLE corpus.diplomacy_event ADD CONSTRAINT diplomacy_event_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES corpus.campaign;
ALTER TABLE corpus.diplomacy_event ADD CONSTRAINT diplomacy_event_kind_id_fkey FOREIGN KEY (kind_id) REFERENCES dict.enum;
ALTER TABLE corpus.diplomacy_event ADD CONSTRAINT diplomacy_event_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES dict.enum;
ALTER TABLE corpus.diplomacy_event ADD CONSTRAINT diplomacy_event_faction_id_fkey FOREIGN KEY (faction_id) REFERENCES dict.faction;
ALTER TABLE corpus.diplomacy_event ADD CONSTRAINT diplomacy_event_gift_id_fkey FOREIGN KEY (gift_id) REFERENCES dict.enum;
ALTER TABLE corpus.diplomacy_event ADD CONSTRAINT diplomacy_event_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES dict.enum;
CREATE INDEX diplomacy_event_campaign ON corpus.diplomacy_event (campaign_id, event_id);
CREATE INDEX diplomacy_event_ts ON corpus.diplomacy_event (ts);
ALTER TABLE corpus.postmortem ADD CONSTRAINT postmortem_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES corpus.campaign;
ALTER TABLE corpus.postmortem ADD CONSTRAINT postmortem_faction_id_fkey FOREIGN KEY (faction_id) REFERENCES dict.faction;
ALTER TABLE corpus.postmortem ADD CONSTRAINT postmortem_outcome_id_fkey FOREIGN KEY (outcome_id) REFERENCES dict.enum;
CREATE INDEX postmortem_campaign ON corpus.postmortem (campaign_id);
CREATE INDEX postmortem_ts ON corpus.postmortem (ts);
ALTER TABLE corpus.postmortem_growth_metric ADD CONSTRAINT postmortem_growth_metric_postmortem_id_fkey FOREIGN KEY (postmortem_id) REFERENCES corpus.postmortem;
ALTER TABLE corpus.ucb_pick ADD CONSTRAINT ucb_pick_campaign_map_id_fkey FOREIGN KEY (campaign_map_id) REFERENCES dict.campaign_map;
ALTER TABLE corpus.ucb_pick ADD CONSTRAINT ucb_pick_faction_id_fkey FOREIGN KEY (faction_id) REFERENCES dict.faction;
CREATE INDEX ucb_pick_ts ON corpus.ucb_pick (ts);
ALTER TABLE corpus.ucb_pick_row ADD CONSTRAINT ucb_pick_row_pick_id_fkey FOREIGN KEY (pick_id) REFERENCES corpus.ucb_pick;
ALTER TABLE corpus.ucb_pick_row ADD CONSTRAINT ucb_pick_row_campaign_map_id_fkey FOREIGN KEY (campaign_map_id) REFERENCES dict.campaign_map;
ALTER TABLE corpus.ucb_pick_row ADD CONSTRAINT ucb_pick_row_faction_id_fkey FOREIGN KEY (faction_id) REFERENCES dict.faction;
ALTER TABLE corpus.campaign ADD FOREIGN KEY (ucb_pick_id) REFERENCES corpus.ucb_pick;
CREATE INDEX rpc_request_ts ON corpus.rpc_request (ts);
CREATE INDEX rpc_response_ts ON corpus.rpc_response (ts);
ALTER TABLE corpus.campaign ADD FOREIGN KEY (segment_id) REFERENCES ops.launch;
ALTER TABLE ops.trial_campaign ADD CONSTRAINT trial_campaign_trial_fkey FOREIGN KEY (trial) REFERENCES ops.trial;
ALTER TABLE ops.trial_campaign ADD CONSTRAINT trial_campaign_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES corpus.campaign;
ALTER TABLE ops.trial_policy ADD CONSTRAINT trial_policy_trial_fkey FOREIGN KEY (trial) REFERENCES ops.trial;
ALTER TABLE ops.trial_policy ADD CONSTRAINT trial_policy_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES dict.enum;
ALTER TABLE ops.trial_outcome ADD CONSTRAINT trial_outcome_trial_fkey FOREIGN KEY (trial) REFERENCES ops.trial;
ALTER TABLE ops.trial_outcome ADD CONSTRAINT trial_outcome_outcome_id_fkey FOREIGN KEY (outcome_id) REFERENCES dict.enum;
CREATE UNIQUE INDEX manifest_live ON ops.manifest (status) WHERE status = 'live';
ALTER TABLE ops.manifest_pack ADD CONSTRAINT manifest_pack_build_id_fkey FOREIGN KEY (build_id) REFERENCES ops.manifest;
ALTER TABLE ops.column_meta ADD CONSTRAINT column_meta_tbl_fkey FOREIGN KEY (tbl) REFERENCES ops.table_meta;
ALTER TABLE analytics.model_agreement ADD CONSTRAINT model_agreement_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES corpus.decision;
CREATE INDEX model_agreement_pair_ts ON analytics.model_agreement (pair, ts) WHERE status = 'ok';
ALTER TABLE analytics.acquisition ADD CONSTRAINT acquisition_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES corpus.campaign;
CREATE INDEX acquisition_family_key ON analytics.acquisition (family, key_id) INCLUDE (campaign_id, acquired_turn, ranks);
ALTER TABLE analytics.item_event ADD CONSTRAINT item_event_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES corpus.campaign;
ALTER TABLE analytics.item_event ADD CONSTRAINT item_event_character_id_fkey FOREIGN KEY (character_id) REFERENCES corpus.character;
ALTER TABLE analytics.item_event ADD CONSTRAINT item_event_ancillary_id_fkey FOREIGN KEY (ancillary_id) REFERENCES dict.ancillary;
CREATE INDEX item_event_campaign ON analytics.item_event (campaign_id, character_id, snapshot_id);
CREATE INDEX item_event_ancillary ON analytics.item_event (ancillary_id, kind);
